import { BRANDS } from './brands';
import { importProductImages, FALLBACK_IMAGE } from './catalogGenerator';

/**
 * Catálogo Oficial de Produtos Bagless
 * 40 Marcas com múltiplos produtos coerentes por escalão (Económico, Médio, Luxo)
 * Ordenado por preço do mais barato ao mais caro.
 */

const RAW_PRODUCTS = [
  // ==========================================
  // PRIMARK (Económico)
  // ==========================================
  {
    id: 'prod-primark-socks-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Pack 5 Pares Meias Algodão Primark',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 6,
    fullPurchasePrice: 6,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['35-38', '39-42', '43-46'],
    colors: ['Branco', 'Preto'],
    description: 'Pack de 5 pares de meias respiráveis em algodão macio para o dia a dia.'
  },
  {
    id: 'prod-primark-tshirt-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'T-Shirt Básica Gola Redonda Primark',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 7,
    fullPurchasePrice: 7,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto', 'Cinzento'],
    description: 'T-shirt básica leve em 100% algodão para uma viagem confortável.'
  },
  {
    id: 'prod-primark-underwear-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Pack 3 Boxer Shorts Algodão Primark',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'underwear',
    price: 8,
    fullPurchasePrice: 8,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Azul-Marinho'],
    description: 'Pack de 3 boxers em algodão com cintura elástica.'
  },
  {
    id: 'prod-primark-swimwear-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Calção de Banho Quick-Dry Primark',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'swimwear',
    price: 12,
    fullPurchasePrice: 12,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L'],
    colors: ['Azul', 'Terracota', 'Verde'],
    description: 'Calções de banho leves com secagem rápida para dias de praia.'
  },
  {
    id: 'prod-primark-sneakers-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Sapatilhas Canvas Low Top Primark',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 16,
    fullPurchasePrice: 16,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['37', '38', '39', '40', '41', '42'],
    colors: ['Branco', 'Preto'],
    description: 'Sapatilhas de lona leve para passeios casuais na cidade.'
  },
  {
    id: 'prod-primark-trousers-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Calça Chino Stretch Primark',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'trousers',
    price: 18,
    fullPurchasePrice: 18,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['38', '40', '42'],
    colors: ['Bege', 'Azul-Marinho'],
    description: 'Calça chino confortável com elastano para maior flexibilidade.'
  },

  // ==========================================
  // H&M (Económico)
  // ==========================================
  {
    id: 'prod-hm-socks-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Pack 7 Pares Meias Invisíveis H&M',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 10,
    fullPurchasePrice: 10,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['36-39', '40-43'],
    colors: ['Branco', 'Nude'],
    description: 'Meias curtas invisíveis com banda em silicone no calcanhar.'
  },
  {
    id: 'prod-hm-tshirt-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Pack 3 T-Shirts Regular Fit H&M',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 18,
    fullPurchasePrice: 18,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto', 'Bege'],
    description: 'T-shirts básicas em algodão jersey macio de corte clássico.'
  },
  {
    id: 'prod-hm-shirt-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Camisa Linen-Blend Resort H&M',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'shirt',
    price: 25,
    fullPurchasePrice: 25,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege', 'Branco', 'Verde-Oliva'],
    description: 'Camisa fresca em mistura de linho e algodão com gola resort.'
  },
  {
    id: 'prod-hm-dress-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Vestido Slip Dress Floral H&M',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'dress',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Estampado Floral', 'Preto'],
    description: 'Vestido fluido com alças finas reguláveis em tecido acetinado.'
  },
  {
    id: 'prod-hm-jacket-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Casaco Puffer Lightweight H&M',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'jacket',
    price: 49,
    fullPurchasePrice: 49,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Bege'],
    description: 'Casaco acolchoado leve e repelente de água com bolsa de arrumação.'
  },

  // ==========================================
  // UNIQLO (Económico)
  // ==========================================
  {
    id: 'prod-uniqlo-socks-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Pack 3 Pares Meias AIRism Uniqlo',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 12,
    fullPurchasePrice: 12,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Preto', 'Branco'],
    description: 'Meias com tecnologia AIRism de secagem ultra-rápida anti-odor.'
  },
  {
    id: 'prod-uniqlo-underwear-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Pack 2 Cuecas Boxers AIRism Seamless Uniqlo',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'underwear',
    price: 15,
    fullPurchasePrice: 15,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Azul-Marinho'],
    description: 'Boxers sem costuras invisíveis sob a roupa para máximo conforto.'
  },
  {
    id: 'prod-uniqlo-tshirt-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'T-Shirt AIRism Cotton Oversized Uniqlo',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 19,
    fullPurchasePrice: 19,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto', 'Bege', 'Verde-Oliva'],
    description: 'T-shirt de caimento oversized com exterior de algodão e interior AIRism fresco.'
  },
  {
    id: 'prod-uniqlo-shirt-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Camisa 100% Linho Premium Uniqlo',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'shirt',
    price: 39,
    fullPurchasePrice: 39,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Azul-Bebe', 'Bege'],
    description: 'Camisa confeccionada em 100% linho europeu de fibras longas.'
  },
  {
    id: 'prod-uniqlo-trousers-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Calça Smart Ankle Chino Uniqlo',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'trousers',
    price: 45,
    fullPurchasePrice: 45,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege', 'Preto', 'Azul-Marinho'],
    description: 'Calça chino com elasticidade bi-direcional e altura pelo tornozelo.'
  },
  {
    id: 'prod-uniqlo-jacket-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Casaco Ultra Light Down Uniqlo',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'jacket',
    price: 69,
    fullPurchasePrice: 69,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Azul-Marinho', 'Castanho'],
    description: 'O famoso casaco de penas ultra-leve e dobrável em bolsa compacta.'
  },

  // ==========================================
  // ZARA (Económico)
  // ==========================================
  {
    id: 'prod-zara-socks-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Pack 3 Pares Meias Ribbed Zara',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 12,
    fullPurchasePrice: 12,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Ecru', 'Preto'],
    description: 'Meias de cano médio em malha canelada de algodão.'
  },
  {
    id: 'prod-zara-tshirt-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'T-Shirt Heavyweight Cotton Zara',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 19,
    fullPurchasePrice: 19,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Terracota', 'Preto'],
    description: 'T-shirt em algodão denso de toque estruturado premium.'
  },
  {
    id: 'prod-zara-shirt-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Camisa 100% Linho Riviera Zara',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'shirt',
    price: 39,
    fullPurchasePrice: 39,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege Natural', 'Branco', 'Azul-Celeste'],
    description: 'Camisa de linho lavado com caimento descontraído de verão.'
  },
  {
    id: 'prod-zara-dress-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Vestido Satin Midi Slip Zara',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'dress',
    price: 45,
    fullPurchasePrice: 45,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Terracota', 'Preto'],
    description: 'Vestido midi em tecido de cetim fluido com escote em V.'
  },
  {
    id: 'prod-zara-blazer-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Blazer Structured Linen Blend Zara',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'blazer',
    price: 79,
    fullPurchasePrice: 79,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['38', '40', '42', '44'],
    colors: ['Bege', 'Preto'],
    description: 'Blazer estruturado em mistura de linho leve com lapela de entalhe.'
  },

  // ==========================================
  // BERSHKA & PULL & BEAR & MANGO & GAP & LEVI'S (Económico)
  // ==========================================
  {
    id: 'prod-bershka-tshirt-1',
    brandId: 'bershka',
    brandName: 'Bershka',
    brand: 'Bershka',
    name: 'T-Shirt Graphic Print Bershka',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 15,
    fullPurchasePrice: 15,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Branco'],
    description: 'T-shirt com estampado gráfico urbano e corte moderno.'
  },
  {
    id: 'prod-bershka-trousers-1',
    brandId: 'bershka',
    brandName: 'Bershka',
    brand: 'Bershka',
    name: 'Calça Cargo Baggy Fit Bershka',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'trousers',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['36', '38', '40', '42'],
    colors: ['Caqui', 'Preto'],
    description: 'Calça cargo solta com bolsos laterais utilitários.'
  },
  {
    id: 'prod-pullbear-swimwear-1',
    brandId: 'pull-and-bear',
    brandName: 'Pull & Bear',
    brand: 'Pull & Bear',
    name: 'Calção de Banho Printed P&B',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'swimwear',
    price: 19,
    fullPurchasePrice: 19,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L'],
    colors: ['Estampado Palm'],
    description: 'Calção de banho leve com padrão tropical surfista.'
  },
  {
    id: 'prod-pullbear-shirt-1',
    brandId: 'pull-and-bear',
    brandName: 'Pull & Bear',
    brand: 'Pull & Bear',
    name: 'Camisa Hawaiian Resort P&B',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'shirt',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Estampado Floral', 'Branco'],
    description: 'Camisa fresca de gola aberta com padrão de férias.'
  },
  {
    id: 'prod-mango-tshirt-1',
    brandId: 'mango',
    brandName: 'Mango',
    brand: 'Mango',
    name: 'T-Shirt 100% Algodão Orgânico Mango',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 18,
    fullPurchasePrice: 18,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege', 'Branco', 'Terracota'],
    description: 'T-shirt de inspiração mediterrânica em algodão sustentável.'
  },
  {
    id: 'prod-mango-sandals-1',
    brandId: 'mango',
    brandName: 'Mango',
    brand: 'Mango',
    name: 'Sandálias em Pele Leather Mango',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sandals',
    price: 49,
    fullPurchasePrice: 49,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['36', '37', '38', '39', '40'],
    colors: ['Tan', 'Preto'],
    description: 'Sandálias rasas em pele bovina com tiras cruzadas.'
  },
  {
    id: 'prod-gap-tshirt-1',
    brandId: 'gap',
    brandName: 'Gap',
    brand: 'Gap',
    name: 'Pack 3 T-Shirts Pocket Gap',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Cinzento', 'Azul'],
    description: 'T-shirts confortáveis com bolso no peito em 100% algodão.'
  },
  {
    id: 'prod-gap-hoodie-1',
    brandId: 'gap',
    brandName: 'Gap',
    brand: 'Gap',
    name: 'Hoodie Arch Logo Fleece Gap',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'jacket',
    price: 59,
    fullPurchasePrice: 59,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cinzento-Mescla', 'Azul-Marinho'],
    description: 'O clássico casaco com capuz e logótipo Gap bordado.'
  },
  {
    id: 'prod-levis-socks-1',
    brandId: 'levis',
    brandName: "Levi's",
    brand: "Levi's",
    name: "Pack 2 Pares Meias Tab Logo Levi's",
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 14,
    fullPurchasePrice: 14,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Branco', 'Preto'],
    description: "Meias caneladas com a mítica etiqueta Red Tab da Levi's."
  },
  {
    id: 'prod-levis-tshirt-1',
    brandId: 'levis',
    brandName: "Levi's",
    brand: "Levi's",
    name: "T-Shirt Batwing Logo Levi's",
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto'],
    description: "T-shirt icónica com estampado do logótipo asa de morcego Levi's."
  },
  {
    id: 'prod-levis-jeans-1',
    brandId: 'levis',
    brandName: "Levi's",
    brand: "Levi's",
    name: "Jeans 501 Original Straight Fit Levi's",
    tier: 'eco',
    category: 'roupa',
    subCategory: 'trousers',
    price: 99,
    fullPurchasePrice: 99,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['30', '32', '34', '36'],
    colors: ['Azul Denim Clássico', 'Preto'],
    description: 'Os jeans retos lendários originais criados em 1873 com fecho de botões.'
  },

  // ==========================================
  // ADIDAS & NIKE & PUMA & VANS & CONVERSE (Económico Desportivo)
  // ==========================================
  {
    id: 'prod-adidas-socks-1',
    brandId: 'adidas',
    brandName: 'Adidas',
    brand: 'Adidas',
    name: 'Pack 3 Pares Meias Cushioned Crew Adidas',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 14,
    fullPurchasePrice: 14,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['39-42', '43-46'],
    colors: ['Branco', 'Preto'],
    description: 'Meias de cano alto com acolchoamento na planta do pé.'
  },
  {
    id: 'prod-adidas-sneakers-1',
    brandId: 'adidas',
    brandName: 'Adidas',
    brand: 'Adidas',
    name: 'Sapatilhas Stan Smith Leather Adidas',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 95,
    fullPurchasePrice: 95,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Branco/Verde', 'Branco/Preto'],
    description: 'Sapatilhas intemporais em pele branca com pormenor verde no calcanhar.'
  },
  {
    id: 'prod-nike-socks-1',
    brandId: 'nike',
    brandName: 'Nike',
    brand: 'Nike',
    name: 'Pack 3 Pares Meias Everyday Cushion Nike',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 16,
    fullPurchasePrice: 16,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['38-42', '42-46'],
    colors: ['Branco', 'Preto'],
    description: 'Meias desportivas com tecnologia Dri-FIT que absorve a transpiração.'
  },
  {
    id: 'prod-nike-sneakers-1',
    brandId: 'nike',
    brandName: 'Nike',
    brand: 'Nike',
    name: "Sapatilhas Air Force 1 '07 Nike",
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 119,
    fullPurchasePrice: 119,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['38', '39', '40', '41', '42', '43', '44'],
    colors: ['Branco Triplo', 'Preto'],
    description: 'As lendárias sapatilhas de basquetebol em pele branca impecável.'
  },
  {
    id: 'prod-puma-sneakers-1',
    brandId: 'puma',
    brandName: 'Puma',
    brand: 'Puma',
    name: 'Sapatilhas Suede Classic Puma',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 79,
    fullPurchasePrice: 79,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['38', '39', '40', '41', '42'],
    colors: ['Preto/Branco', 'Azul-Marinho'],
    description: 'Sapatilhas clássicas em camurça macia com a risca Formstrip.'
  },
  {
    id: 'prod-vans-sneakers-1',
    brandId: 'vans',
    brandName: 'Vans',
    brand: 'Vans',
    name: 'Sapatilhas Old Skool Canvas Vans',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 75,
    fullPurchasePrice: 75,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['37', '38', '39', '40', '41', '42'],
    colors: ['Preto/Branco', 'Azul'],
    description: 'Sapatilhas skate de cano baixo com a lendária risca Sidestripe.'
  },
  {
    id: 'prod-converse-sneakers-1',
    brandId: 'converse',
    brandName: 'Converse',
    brand: 'Converse',
    name: 'Sapatilhas Chuck Taylor All Star High Converse',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 75,
    fullPurchasePrice: 75,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['37', '38', '39', '40', '41', '42'],
    colors: ['Preto', 'Branco', 'Vermelho'],
    description: 'As sapatilhas de lona de cano alto mais famosas da história.'
  },

  // ==========================================
  // ESCALÃO MÉDIO (MÉDIO - tier: 'mid')
  // ==========================================
  {
    id: 'prod-tommy-socks-1',
    brandId: 'tommy-hilfiger',
    brandName: 'Tommy Hilfiger',
    brand: 'Tommy Hilfiger',
    name: 'Pack 2 Pares Meias Flag Tommy Hilfiger',
    tier: 'mid',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 22,
    fullPurchasePrice: 22,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Azul-Marinho', 'Branco'],
    description: 'Meias finas em algodão com bordado da bandeira Tommy.'
  },
  {
    id: 'prod-tommy-tshirt-1',
    brandId: 'tommy-hilfiger',
    brandName: 'Tommy Hilfiger',
    brand: 'Tommy Hilfiger',
    name: 'Polo Icon Flex Cotton Tommy Hilfiger',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 89,
    fullPurchasePrice: 89,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul-Marinho', 'Branco', 'Vermelho'],
    description: 'Polo em piqué de algodão com toque suave e bandeira no peito.'
  },
  {
    id: 'prod-ck-underwear-1',
    brandId: 'calvin-klein',
    brandName: 'Calvin Klein',
    brand: 'Calvin Klein',
    name: 'Pack 3 Trunk Underwear Cotton Stretch CK',
    tier: 'mid',
    category: 'roupainterior',
    subCategory: 'underwear',
    price: 45,
    fullPurchasePrice: 45,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Cinzento', 'Branco'],
    description: 'Boxers icónicos em algodão com a famosa faixa elástica Calvin Klein.'
  },
  {
    id: 'prod-ck-tshirt-1',
    brandId: 'calvin-klein',
    brandName: 'Calvin Klein',
    brand: 'Calvin Klein',
    name: 'T-Shirt Monogram Logo Calvin Klein',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 49,
    fullPurchasePrice: 49,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto'],
    description: 'T-shirt em algodão orgânico com estampado frontal CK.'
  },
  {
    id: 'prod-ralph-socks-1',
    brandId: 'ralph-lauren',
    brandName: 'Ralph Lauren',
    brand: 'Ralph Lauren',
    name: 'Pack 3 Pares Meias Polo Player Ralph Lauren',
    tier: 'mid',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 35,
    fullPurchasePrice: 35,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Azul-Marinho', 'Bege', 'Preto'],
    description: 'Meias elegantes com bordado do cavalo Polo em contraste.'
  },
  {
    id: 'prod-ralph-tshirt-1',
    brandId: 'ralph-lauren',
    brandName: 'Ralph Lauren',
    brand: 'Ralph Lauren',
    name: 'Polo Custom Slim Fit Polo Ralph Lauren',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 130,
    fullPurchasePrice: 130,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul-Marinho', 'Branco', 'Verde', 'Rosa-Pale'],
    description: 'O mítico polo de algodão piqué da Polo Ralph Lauren.'
  },
  {
    id: 'prod-superdry-tshirt-1',
    brandId: 'superdry',
    brandName: 'Superdry',
    brand: 'Superdry',
    name: 'T-Shirt Vintage Logo Superdry',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 35,
    fullPurchasePrice: 35,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cinzento-Mescla', 'Azul'],
    description: 'T-shirt em algodão macio com o estampado vintage Superdry.'
  },
  {
    id: 'prod-diesel-jeans-1',
    brandId: 'diesel',
    brandName: 'Diesel',
    brand: 'Diesel',
    name: 'Jeans 1979 Sleenker Slim Denim Diesel',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'trousers',
    price: 190,
    fullPurchasePrice: 190,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['30', '32', '34'],
    colors: ['Azul Denim Escuro'],
    description: 'Jeans slim de confeção italiana com lavagem vintage premium.'
  },
  {
    id: 'prod-mk-wallet-1',
    brandId: 'michael-kors',
    brandName: 'Michael Kors',
    brand: 'Michael Kors',
    name: 'Carteira Leather Card Case Michael Kors',
    tier: 'mid',
    category: 'acessorios',
    subCategory: 'wallet',
    price: 75,
    fullPurchasePrice: 75,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Preto', 'Castanho MK'],
    description: 'Porta-cartões compacto em pele granulada com placa metálica MK.'
  },
  {
    id: 'prod-mk-bag-1',
    brandId: 'michael-kors',
    brandName: 'Michael Kors',
    brand: 'Michael Kors',
    name: 'Mala de Ombro Jet Set Leather Michael Kors',
    tier: 'mid',
    category: 'acessorios',
    subCategory: 'bag',
    price: 275,
    fullPurchasePrice: 275,
    gender: 'feminino',
    occasion: 'cidade',
    sizes: ['Média'],
    colors: ['Preto', 'Bege'],
    description: 'Mala de ombro em pele Saffiano resistente ideal para viagens.'
  },
  {
    id: 'prod-boss-blazer-1',
    brandId: 'hugo-boss',
    brandName: 'Hugo Boss',
    brand: 'Hugo Boss',
    name: 'Fato Tailored Wool Blend Suit Hugo Boss',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'blazer',
    price: 690,
    fullPurchasePrice: 690,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['48', '50', '52', '54'],
    colors: ['Azul-Marinho', 'Cinzento-Escuro'],
    description: 'Fato completo de corte impecável em lã virgem italiana.'
  },
  {
    id: 'prod-lacoste-polo-1',
    brandId: 'lacoste',
    brandName: 'Lacoste',
    brand: 'Lacoste',
    name: 'Polo L.12.12 Classic Fit Lacoste',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 110,
    fullPurchasePrice: 110,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Verde-Crocodilo', 'Branco', 'Azul'],
    description: 'O polo de ténis original criado por René Lacoste em 1933.'
  },
  {
    id: 'prod-tnf-jacket-1',
    brandId: 'the-north-face',
    brandName: 'The North Face',
    brand: 'The North Face',
    name: 'Casaco Puffer Nuptse 1996 Down Jacket TNF',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'jacket',
    price: 340,
    fullPurchasePrice: 340,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Azul-Cobalto'],
    description: 'O lendário casaco de penas térmico com enchimento de penas 700 fill.'
  },
  {
    id: 'prod-guess-bag-1',
    brandId: 'guess',
    brandName: 'Guess',
    brand: 'Guess',
    name: 'Mala Handbag Logo Print Guess',
    tier: 'mid',
    category: 'acessorios',
    subCategory: 'bag',
    price: 160,
    fullPurchasePrice: 160,
    gender: 'feminino',
    occasion: 'cidade',
    sizes: ['Média'],
    colors: ['Castanho Logo', 'Preto'],
    description: 'Mala estruturada com estampado 4G monograma da Guess.'
  },
  {
    id: 'prod-ax-sneakers-1',
    brandId: 'armani-exchange',
    brandName: 'Armani Exchange',
    brand: 'Armani Exchange',
    name: 'Sapatilhas Urban Runner Armani Exchange',
    tier: 'mid',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 140,
    fullPurchasePrice: 140,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['40', '41', '42', '43'],
    colors: ['Preto/Branco'],
    description: 'Sapatilhas urbanas confortáveis com o logótipo A|X sobressaído.'
  },

  // ==========================================
  // ESCALÃO LUXO (LUXO - tier: 'luxury')
  // ==========================================
  {
    id: 'prod-versace-underwear-1',
    brandId: 'versace',
    brandName: 'Versace',
    brand: 'Versace',
    name: 'Boxer Brief Barocco Print Versace',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'underwear',
    price: 95,
    fullPurchasePrice: 95,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L'],
    colors: ['Preto/Dourado Barocco'],
    description: 'Boxers em algodão elástico com elástico na cintura em padrão Greca e Medusa.'
  },
  {
    id: 'prod-balenciaga-socks-1',
    brandId: 'balenciaga',
    brandName: 'Balenciaga',
    brand: 'Balenciaga',
    name: 'Meias Balenciaga Tennis Logo Socks',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 110,
    fullPurchasePrice: 110,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Branco/Preto'],
    description: 'Meias de ténis em malha canelada com o logótipo Balenciaga tricotado.'
  },
  {
    id: 'prod-hermes-socks-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Meias em Algodão Mercerizado Hermès',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 120,
    fullPurchasePrice: 120,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['39-42', '43-46'],
    colors: ['Azul-Marinho', 'Preto'],
    description: 'Meias ultra-refinadas em algodão egípcio mercerizado com detalhe discreto H.'
  },
  {
    id: 'prod-gucci-socks-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Meias GG Monogram Cotton Blend Gucci',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 130,
    fullPurchasePrice: 130,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L'],
    colors: ['Bege/Castanho GG'],
    description: 'Meias de luxo com o lendário padrão monograma GG de Guccio Gucci.'
  },
  {
    id: 'prod-lv-socks-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Meias Monogram Jacquard Cotton Louis Vuitton',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 140,
    fullPurchasePrice: 140,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['M', 'L'],
    colors: ['Preto', 'Castanho Monogram'],
    description: 'Meias em jacquard de algodão fino tecidas com o icónico padrão Monogram.'
  },
  {
    id: 'prod-prada-socks-1',
    brandId: 'prada',
    brandName: 'Prada',
    brand: 'Prada',
    name: 'Pack 3 Pares Meias Prada Triangle Logo',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    price: 150,
    fullPurchasePrice: 150,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['M', 'L'],
    colors: ['Preto', 'Branco'],
    description: 'Meias de algodão de malha fina com o emblema em triângulo Prada.'
  },
  {
    id: 'prod-jacquemus-hat-1',
    brandId: 'jacquemus',
    brandName: 'Jacquemus',
    brand: 'Jacquemus',
    name: 'Chapéu Le Bob Artichaut Bucket Jacquemus',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    price: 150,
    fullPurchasePrice: 150,
    gender: 'unissex',
    occasion: 'praia',
    sizes: ['Único'],
    colors: ['Bege', 'Preto'],
    description: 'O famoso chapéu bucket de abas desfiadas com cordão ajustável.'
  },
  {
    id: 'prod-chanel-perfume-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Perfume Chanel N°5 Eau de Parfum 100ml',
    tier: 'luxury',
    category: 'perfumes',
    subCategory: 'perfume',
    price: 165,
    fullPurchasePrice: 165,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['100ml'],
    colors: ['Âmbar'],
    description: 'O perfume mais mítico do mundo criado por Coco Chanel em 1921.'
  },
  {
    id: 'prod-hermes-perfume-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: "Perfume Terre d'Hermès Eau de Parfum 100ml",
    tier: 'luxury',
    category: 'perfumes',
    subCategory: 'perfume',
    price: 165,
    fullPurchasePrice: 165,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['100ml'],
    colors: ['Âmbar'],
    description: 'Uma fragrância mineral e amadeirada que liga o homem às suas origens.'
  },
  {
    id: 'prod-acne-scarf-1',
    brandId: 'acne-studios',
    brandName: 'Acne Studios',
    brand: 'Acne Studios',
    name: 'Cachecol de Lã Alpaca Face Patch Acne Studios',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    price: 240,
    fullPurchasePrice: 240,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Rosa-Pálido', 'Cinzento'],
    description: 'Cachecol em mistura de lã alpaca ultra-macia com o patch emoji Face.'
  },
  {
    id: 'prod-lv-perfume-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: "Perfume L'Immensité EDP 100ml Louis Vuitton",
    tier: 'luxury',
    category: 'perfumes',
    subCategory: 'perfume',
    price: 290,
    fullPurchasePrice: 290,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['100ml'],
    colors: ['Cristal'],
    description: 'Fragrância de viagem com notas de gengibre, toranja e âmbar amadeirado.'
  },
  {
    id: 'prod-jacquemus-shirt-1',
    brandId: 'jacquemus',
    brandName: 'Jacquemus',
    brand: 'Jacquemus',
    name: 'Camisa de Linho La Chemise Jean Jacquemus',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'shirt',
    price: 320,
    fullPurchasePrice: 320,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege Natural', 'Azul-Céu'],
    description: 'Camisa de linho desconstruída com o logótipo Jacquemus bordado no bolso.'
  },
  {
    id: 'prod-loewe-wallet-1',
    brandId: 'loewe',
    brandName: 'LOEWE',
    brand: 'LOEWE',
    name: 'Carteira Puzzle Leather Cardholder LOEWE',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'wallet',
    price: 320,
    fullPurchasePrice: 320,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Tan/Castanho', 'Preto'],
    description: 'Porta-cartões em pele de bezerro com o mítico corte geométrico Puzzle.'
  },
  {
    id: 'prod-acne-jeans-1',
    brandId: 'acne-studios',
    brandName: 'Acne Studios',
    brand: 'Acne Studios',
    name: 'Jeans Straight Fit Loose Denim Acne Studios',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'trousers',
    price: 340,
    fullPurchasePrice: 340,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['30', '32', '34'],
    colors: ['Azul Vintage Wash'],
    description: 'Denim rígido de alta qualidade com corte direto descontraído.'
  },
  {
    id: 'prod-loewe-sunglasses-1',
    brandId: 'loewe',
    brandName: 'LOEWE',
    brand: 'LOEWE',
    name: "Óculos de Sol Paula's Ibiza LOEWE",
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'sunglasses',
    price: 380,
    fullPurchasePrice: 380,
    gender: 'unissex',
    occasion: 'praia',
    sizes: ['Único'],
    colors: ['Branco', 'Preto'],
    description: 'Óculos de sol em acetato escultural inspirados no espírito livre de Ibiza.'
  },
  {
    id: 'prod-lv-wallet-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Carteira Pocket Organizer Monogram Louis Vuitton',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'wallet',
    price: 380,
    fullPurchasePrice: 380,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Monogram Canvas'],
    description: 'Carteira compacta lendária em lona Monogram com acabamento em pele.'
  },
  {
    id: 'prod-saint-laurent-sunglasses-1',
    brandId: 'saint-laurent',
    brandName: 'Saint Laurent',
    brand: 'Saint Laurent',
    name: 'Óculos de Sol Acetato Black YSL Saint Laurent',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'sunglasses',
    price: 390,
    fullPurchasePrice: 390,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Preto'],
    description: 'Óculos de sol pretos com armação em acetato e assinatura YSL gravada.'
  },
  {
    id: 'prod-common-sneakers-1',
    brandId: 'common-projects',
    brandName: 'Common Projects',
    brand: 'Common Projects',
    name: 'Sapatilhas Original Achilles Low White Common Projects',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 420,
    fullPurchasePrice: 420,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Branco com Números Dourados'],
    description: 'A referência máxima de sapatilhas de luxo minimalistas feitas à mão em Itália.'
  },
  {
    id: 'prod-saint-laurent-tshirt-1',
    brandId: 'saint-laurent',
    brandName: 'Saint Laurent',
    brand: 'Saint Laurent',
    name: 'T-Shirt Cotton Logo Saint Laurent',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 420,
    fullPurchasePrice: 420,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Branco'],
    description: 'T-shirt em jersey de algodão ultra-fino com corte rock parisiense.'
  },
  {
    id: 'prod-hermes-scarf-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Lenço de Seda Twilly Printed Hermès',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    price: 420,
    fullPurchasePrice: 420,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['Único'],
    colors: ['Laranja Hermès / Multicolor'],
    description: 'Fita/lenço em seda pura impressa à mão pelos artesãos de Lyon.'
  },
  {
    id: 'prod-gucci-belt-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Cinto GG Marmont Leather Belt Gucci',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'belt',
    price: 450,
    fullPurchasePrice: 450,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['85cm', '90cm', '95cm', '100cm'],
    colors: ['Preto com Fivela Dourada'],
    description: 'Cinto em pele lisa com a fivela com o duplo G icónico em latão dourado.'
  },
  {
    id: 'prod-rolex-pouch-1',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Bolsa de Viagem em Pele para Relógio Rolex',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    price: 450,
    fullPurchasePrice: 450,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['Único'],
    colors: ['Verde Rolex'],
    description: 'Estojo individual de viagem em pele verde oficial com forro em camurça.'
  },
  {
    id: 'prod-burberry-shirt-1',
    brandId: 'burberry',
    brandName: 'Burberry',
    brand: 'Burberry',
    name: 'Camisa Vintage Check Cotton Burberry',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'shirt',
    price: 480,
    fullPurchasePrice: 480,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege Vintage Check'],
    description: 'Camisa em sapatilha de algodão com o padrão de xadrez icónico da marca.'
  },
  {
    id: 'prod-chanel-sunglasses-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Óculos de Sol Acetato Cat-Eye Chanel',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'sunglasses',
    price: 480,
    fullPurchasePrice: 480,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['Único'],
    colors: ['Preto com CC Dourado'],
    description: 'Óculos de sol em acetato preto com detalhes duplos C nas hastes.'
  },
  {
    id: 'prod-balenciaga-tshirt-1',
    brandId: 'balenciaga',
    brandName: 'Balenciaga',
    brand: 'Balenciaga',
    name: 'T-Shirt Oversized Logo Balenciaga',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 490,
    fullPurchasePrice: 490,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Preto', 'Branco'],
    description: 'T-shirt vintage com lavagem desbotada e logótipo frontal Balenciaga.'
  },
  {
    id: 'prod-burberry-scarf-1',
    brandId: 'burberry',
    brandName: 'Burberry',
    brand: 'Burberry',
    name: 'Cachecol em Caxemira Vintage Check Burberry',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    price: 520,
    fullPurchasePrice: 520,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Bege Camel Check'],
    description: 'Cachecol tecido numa fábrica tradicional escocesa com 100% caxemira pura.'
  },
  {
    id: 'prod-lv-belt-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Cinto Initiales 40mm Reversível Louis Vuitton',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'belt',
    price: 520,
    fullPurchasePrice: 520,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['90cm', '95cm', '100cm'],
    colors: ['Monogram / Preto'],
    description: 'Cinto reversível com fivela com iniciais LV em metal prateado.'
  },
  {
    id: 'prod-prada-hat-1',
    brandId: 'prada',
    brandName: 'Prada',
    brand: 'Prada',
    name: 'Chapéu Bucket Re-Nylon Black Prada',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    price: 550,
    fullPurchasePrice: 550,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['M', 'L'],
    colors: ['Preto'],
    description: 'O famoso chapéu bucket em Re-Nylon sustentável com o triângulo esmaltado.'
  },
  {
    id: 'prod-zimmermann-top-1',
    brandId: 'zimmermann',
    brandName: 'Zimmermann',
    brand: 'Zimmermann',
    name: 'Top de Seda Floral Matchmaker Zimmermann',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'tshirt',
    price: 580,
    fullPurchasePrice: 580,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['0', '1', '2'],
    colors: ['Estampado Floral Resort'],
    description: 'Top leve em 100% seda organza com folhos finos delicados.'
  },
  {
    id: 'prod-jacquemus-bag-1',
    brandId: 'jacquemus',
    brandName: 'Jacquemus',
    brand: 'Jacquemus',
    name: 'Carteira Le Chiquito Leather Jacquemus',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    price: 590,
    fullPurchasePrice: 590,
    gender: 'feminino',
    occasion: 'cidade',
    sizes: ['Mini'],
    colors: ['Bege', 'Preto', 'Terracota'],
    description: 'A micro-mala em pele estruturada de asa rígida mais desejada.'
  },
  {
    id: 'prod-loewe-bag-1',
    brandId: 'loewe',
    brandName: 'LOEWE',
    brand: 'LOEWE',
    name: 'Mala Ráfia Anagram Basket Tote LOEWE',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    price: 690,
    fullPurchasePrice: 690,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['Média'],
    colors: ['Natural Palm / Tan Leather'],
    description: 'Cesto de praia tecido à mão em folhas de palmeira com asas em pele bovina.'
  },
  {
    id: 'prod-hermes-belt-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Cinto em Pele de Bezerro H Buckle Hermès',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'belt',
    price: 780,
    fullPurchasePrice: 780,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['85cm', '90cm', '95cm'],
    colors: ['Laranja Hermès / Preto'],
    description: 'Cinto reversível em pele Togo de grão refinado com a mítica fivela em H.'
  },
  {
    id: 'prod-gucci-loafers-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Mocassins Horsebit Leather Loafers Gucci',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'loafers',
    price: 850,
    fullPurchasePrice: 850,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['Preto', 'Castanho-Escuro'],
    description: 'Os lendários mocassins italianos criados em 1953 com travessão em latão.'
  },
  {
    id: 'prod-versace-sneakers-1',
    brandId: 'versace',
    brandName: 'Versace',
    brand: 'Versace',
    name: 'Sapatilhas Trigreca Sneakers Versace',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 890,
    fullPurchasePrice: 890,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['40', '41', '42', '43'],
    colors: ['Branco/Dourado Barocco'],
    description: 'Sapatilhas esculturais com relevos no solado em padrão Greca.'
  },
  {
    id: 'prod-balenciaga-sneakers-1',
    brandId: 'balenciaga',
    brandName: 'Balenciaga',
    brand: 'Balenciaga',
    name: 'Sapatilhas Triple S Chunky Sneakers Balenciaga',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 950,
    fullPurchasePrice: 950,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Branco/Cinzento/Preto'],
    description: 'As sapatilhas sobredimensionadas com sola tripla moldada de culto global.'
  },
  {
    id: 'prod-zimmermann-dress-1',
    brandId: 'zimmermann',
    brandName: 'Zimmermann',
    brand: 'Zimmermann',
    name: 'Vestido Matchmaker Floral Silk Midi Zimmermann',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'dress',
    price: 950,
    fullPurchasePrice: 950,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['0', '1', '2'],
    colors: ['Estampado Floral Victorian'],
    description: 'Vestido de alta-costura em seda pura com cinto e estampado floral artesanal.'
  },
  {
    id: 'prod-acne-coat-1',
    brandId: 'acne-studios',
    brandName: 'Acne Studios',
    brand: 'Acne Studios',
    name: 'Casaco Wool Blend Oversized Coat Acne Studios',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    price: 1100,
    fullPurchasePrice: 1100,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['46', '48', '50'],
    colors: ['Camel', 'Preto'],
    description: 'Sobretudo duplo em malha de lã estruturada de caimento arquitetónico.'
  },
  {
    id: 'prod-versace-shirt-1',
    brandId: 'versace',
    brandName: 'Versace',
    brand: 'Versace',
    name: 'Camisa em Seda Barocco Print Versace',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'shirt',
    price: 1150,
    fullPurchasePrice: 1150,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['48', '50', '52'],
    colors: ['Barocco Dourado/Preto'],
    description: 'Camisa de seda pura twill com a estampa opulenta barroca da maison italiana.'
  },
  {
    id: 'prod-lv-sneakers-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Sapatilhas LV Trainer Leather Louis Vuitton',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'sneakers',
    price: 1150,
    fullPurchasePrice: 1150,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['Branco/Azul LV'],
    description: 'Sapatilhas desenhadas por Virgil Abloh em pele de bezerro com detalhes florais Monogram.'
  },
  {
    id: 'prod-rolex-cufflinks-1',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Botões de Punho Ouro 18k Crown Rolex',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'wallet',
    price: 1800,
    fullPurchasePrice: 1800,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['Único'],
    colors: ['Ouro Amarelo 18k'],
    description: 'Botões de punho oficiais em ouro amarelo maciço de 18 quilates com a coroa Rolex.'
  },
  {
    id: 'prod-loewe-dress-1',
    brandId: 'loewe',
    brandName: 'LOEWE',
    brand: 'LOEWE',
    name: 'Vestido Asymmetrical Linen LOEWE',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'dress',
    price: 1850,
    fullPurchasePrice: 1850,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['36', '38', '40'],
    colors: ['Branco Ecru'],
    description: 'Vestido de linho escultural com corte assimétrico vanguardista.'
  },
  {
    id: 'prod-prada-bag-1',
    brandId: 'prada',
    brandName: 'Prada',
    brand: 'Prada',
    name: 'Mochila Re-Nylon & Leather Prada',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    price: 1850,
    fullPurchasePrice: 1850,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Média'],
    colors: ['Preto'],
    description: 'Mochila utilitária em Re-Nylon com acabamentos em pele Saffiano e fecho de fivela.'
  },
  {
    id: 'prod-gucci-jacket-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Casaco Jacquard GG Monogram Gucci',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    price: 1950,
    fullPurchasePrice: 1950,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['48', '50', '52'],
    colors: ['Castanho GG / Bege'],
    description: 'Casaco com fecho de correr em lona jacquard GG e riscas Web verde e vermelha.'
  },
  {
    id: 'prod-balenciaga-jacket-1',
    brandId: 'balenciaga',
    brandName: 'Balenciaga',
    brand: 'Balenciaga',
    name: 'Casaco Puffer Oversized Balenciaga',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    price: 2100,
    fullPurchasePrice: 2100,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['46', '48', '50'],
    colors: ['Preto Matte'],
    description: 'Puffer volumoso em nylon técnico impermeável com gola alta acolchoada.'
  },
  {
    id: 'prod-gucci-bag-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Mala de Viagem GG Supreme Duffle Gucci',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    price: 2200,
    fullPurchasePrice: 2200,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Grande'],
    colors: ['GG Supreme Ébano'],
    description: 'Mala de viagem fim-de-semana clássica em lona GG Supreme e alça de ombro ajustável.'
  },
  {
    id: 'prod-burberry-coat-1',
    brandId: 'burberry',
    brandName: 'Burberry',
    brand: 'Burberry',
    name: 'Trench Coat Kensington Heritage Burberry',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    price: 2250,
    fullPurchasePrice: 2250,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['48', '50', '52'],
    colors: ['Honey / Bege'],
    description: 'O lendário trench coat britânico duplo em gabardina de algodão impermeável.'
  },
  {
    id: 'prod-prada-blazer-1',
    brandId: 'prada',
    brandName: 'Prada',
    brand: 'Prada',
    name: 'Blazer Re-Nylon Tailored Prada',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'blazer',
    price: 2400,
    fullPurchasePrice: 2400,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['48', '50', '52'],
    colors: ['Preto'],
    description: 'Blazer de alfaiataria em Re-Nylon com bolso de peito com o emblema metálico.'
  },
  {
    id: 'prod-lv-bag-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Mala Keepall Bandoulière 50 Monogram Louis Vuitton',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    price: 2450,
    fullPurchasePrice: 2450,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['50cm'],
    colors: ['Monogram Canvas'],
    description: 'A mala de viagem dobrável em lona Monogram ícone da arte de viajar desde 1930.'
  },
  {
    id: 'prod-chanel-cardigan-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Cardigan de Tweed Wool Blend Chanel',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    price: 2800,
    fullPurchasePrice: 2800,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['36', '38', '40'],
    colors: ['Preto/Branco Tweed'],
    description: 'Casaco de tweed parisiense com botões de joia gravados com o camélia e logo CC.'
  },
  {
    id: 'prod-hermes-coat-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Manteau em Lã e Caxemira Double-Face Hermès',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    price: 3400,
    fullPurchasePrice: 3400,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['48', '50'],
    colors: ['Camel'],
    description: 'Sobretudo longo em lã e caxemira cosido à mão pelos mestres artesãos Hermès.'
  },
  {
    id: 'prod-saint-laurent-jacket-1',
    brandId: 'saint-laurent',
    brandName: 'Saint Laurent',
    brand: 'Saint Laurent',
    name: 'Blusão de Pele Moto Leather Jacket Saint Laurent',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    price: 3900,
    fullPurchasePrice: 3900,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['48', '50', '52'],
    colors: ['Preto'],
    description: 'Blusão de pele de cordeiro macia com fivelas e fechos metálicos em tom prata envelhecida.'
  },
  {
    id: 'prod-chanel-dress-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Vestido Midi Silk Jacquard Chanel',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'dress',
    price: 4200,
    fullPurchasePrice: 4200,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['36', '38', '40'],
    colors: ['Preto'],
    description: 'Vestido midi em seda jacquard preta com caimento impecável de alta-costura.'
  },
  {
    id: 'prod-rolex-watch-1',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio Oyster Perpetual 36mm Steel Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    price: 6200,
    fullPurchasePrice: 6200,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['36mm'],
    colors: ['Oystersteel / Mostrador Turquesa'],
    description: 'Relógio automático em aço Oystersteel com bracelete Oyster e mostrador exclusivo.'
  },
  {
    id: 'prod-chanel-bag-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Mala Clássica Flap Bag Lambskin Chanel',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    price: 8900,
    fullPurchasePrice: 8900,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['Média'],
    colors: ['Preto com CC Dourado'],
    description: 'A mala acolchoada icónica em pele de cordeiro com fecho de fecho giratório CC.'
  },
  {
    id: 'prod-rolex-watch-2',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio Datejust 41mm Fluted Bezel Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    price: 10500,
    fullPurchasePrice: 10500,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['41mm'],
    colors: ['Oystersteel & Ouro Branco'],
    description: 'Relógio de precisão com bisel canelado em ouro branco 18k e bracelete Jubilee.'
  },
  {
    id: 'prod-hermes-bag-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Mala Birkin 30 Togo Leather Hermès',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    price: 12500,
    fullPurchasePrice: 12500,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['30cm'],
    colors: ['Gold / Laranja Hermès'],
    description: 'A mala de mão em pele Togo mais cobiçada e prestigiada da história da moda.'
  },
  {
    id: 'prod-rolex-watch-3',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio Submariner Date 41mm Ceramic Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    price: 14200,
    fullPurchasePrice: 14200,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['41mm'],
    colors: ['Oystersteel / Bisel Cerâmico Preto'],
    description: 'O relógio de mergulho mais famoso do mundo com bisel Cerachrom graduado.'
  },
  {
    id: 'prod-rolex-watch-4',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio GMT-Master II "Pepsi" Steel Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    price: 16800,
    fullPurchasePrice: 16800,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['40mm'],
    colors: ['Oystersteel / Bisel Azul e Vermelho'],
    description: 'O relógio de aviação lendário com bisel rotativo bi-direcional de dois fusos horários.'
  },
  {
    id: 'prod-rolex-watch-5',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio Daytona Cosmograph Gold 18k Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    price: 38000,
    fullPurchasePrice: 38000,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['40mm'],
    colors: ['Ouro Amarelo 18k / Mostrador Preto'],
    description: 'O cronógrafo de corrida definitivo em ouro amarelo maciço de 18 quilates.'
  }
];

// Enrich each item with image fallback, rental rate calculation, and standard flags
export const PRODUCTS = RAW_PRODUCTS.map((item) => {
  const finalPrice = item.price || item.fullPurchasePrice || 50;
  const rentalPricePerDay = Math.max(3, Math.round(finalPrice / 25));
  const image = item.image || importProductImages(item.category, item.subCategory);

  return {
    ...item,
    brand: item.brand || item.brandName,
    brandName: item.brandName || item.brand,
    price: finalPrice,
    fullPurchasePrice: finalPrice,
    rentalPricePerDay,
    image,
    images: [image],
    inStock: true,
    discontinued: false,
    merchantAttribution: `${item.brandName} Partner Network`,
    affiliateUrl: `https://partner.bagless.app/redirect?brand=${item.brandId}&id=${item.id}`,
    weatherTag: item.occasion === 'praia' ? 'Clima Quente' : item.occasion === 'desporto' ? 'Desporto & Aventura' : 'Urbano & Elegante'
  };
}).sort((a, b) => a.price - b.price); // MANDATORY: Sorted by price from cheapest to most expensive

export const DYNAMIC_CATALOG = PRODUCTS;

/**
 * Periodically syncs products from partner feeds
 */
export const syncLiveProductFeeds = async () => {
  console.log(`[Bagless Feed Sync] Catálogo com ${PRODUCTS.length} produtos ordenados por preço.`);
  return PRODUCTS;
};

export { importProductImages, FALLBACK_IMAGE };
