import { BRANDS } from './brands';
import { importProductImages, FALLBACK_IMAGE } from './catalogGenerator';

/**
 * Catálogo Oficial de Produtos Bagless
 * Garantido com produtos dos 3 tiers (Económico, Médio, Luxo) em TODAS as categorias:
 * - Acessórios (acessorios)
 * - Calçado (calcado)
 * - Perfumes (perfumes)
 * - Relógios (relogios)
 * - Roupa (roupa)
 * - Roupa Interior (roupainterior)
 *
 * Ordenado por CATEGORIA e depois por PREÇO (do mais barato ao mais caro).
 */

const RAW_PRODUCTS = [
  // ==========================================
  // 1. ACESSÓRIOS (acessorios)
  // Tiers: Económico (eco), Médio (mid), Luxo (luxury)
  // ==========================================
  // ECO
  {
    id: 'prod-primark-tote-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Mala Canvas Beach Tote Primark',
    tier: 'eco',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=80',
    price: 14,
    fullPurchasePrice: 14,
    gender: 'unissex',
    occasion: 'praia',
    sizes: ['Média'],
    colors: ['Bege Natural'],
    description: 'Mala de lona leve para transporte de essenciais de praia.'
  },
  {
    id: 'prod-hm-hat-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Chapéu Straw Sun Hat H&M',
    tier: 'eco',
    category: 'acessorios',
    subCategory: 'hat',
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=700&q=80',
    price: 18,
    fullPurchasePrice: 18,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['S/M', 'L/XL'],
    colors: ['Palha Natural'],
    description: 'Chapéu de palha entrelaçada com fita em contraste.'
  },
  {
    id: 'prod-uniqlo-hat-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Chapéu Bucket UV Cut Uniqlo',
    tier: 'eco',
    category: 'acessorios',
    subCategory: 'hat',
    image: 'https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=700&q=80',
    price: 19,
    fullPurchasePrice: 19,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['M', 'L'],
    colors: ['Bege', 'Preto'],
    description: 'Chapéu bucket com proteção solar UPF50+ dobrável para viagem.'
  },
  {
    id: 'prod-zara-sunglasses-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Óculos de Sol Acetato Vintage Zara',
    tier: 'eco',
    category: 'acessorios',
    subCategory: 'sunglasses',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=700&q=80',
    price: 25,
    fullPurchasePrice: 25,
    gender: 'unissex',
    occasion: 'praia',
    sizes: ['Único'],
    colors: ['Tartaruga'],
    description: 'Óculos de sol em acetato com proteção UV400 categoria 3.'
  },

  // MID
  {
    id: 'prod-tnf-hat-1',
    brandId: 'the-north-face',
    brandName: 'The North Face',
    brand: 'The North Face',
    name: 'Gorro Knit Logo Beanie TNF',
    tier: 'mid',
    category: 'acessorios',
    subCategory: 'hat',
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=700&q=80',
    price: 32,
    fullPurchasePrice: 32,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['Único'],
    colors: ['Preto'],
    description: 'Gorro térmico de malha acrílica macia com patch TNF.'
  },
  {
    id: 'prod-tommy-belt-1',
    brandId: 'tommy-hilfiger',
    brandName: 'Tommy Hilfiger',
    brand: 'Tommy Hilfiger',
    name: 'Cinto Leather Casual Tommy Hilfiger',
    tier: 'mid',
    category: 'acessorios',
    subCategory: 'belt',
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=700&q=80',
    price: 55,
    fullPurchasePrice: 55,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['85cm', '90cm', '95cm'],
    colors: ['Castanho', 'Preto'],
    description: 'Cinto em pele genuína com fivela metálica escovada.'
  },
  {
    id: 'prod-mk-wallet-1',
    brandId: 'michael-kors',
    brandName: 'Michael Kors',
    brand: 'Michael Kors',
    name: 'Carteira Leather Card Case Michael Kors',
    tier: 'mid',
    category: 'acessorios',
    subCategory: 'wallet',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=700&q=80',
    price: 75,
    fullPurchasePrice: 75,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Preto', 'Castanho MK'],
    description: 'Porta-cartões compacto em pele granulada com placa metálica MK.'
  },
  {
    id: 'prod-guess-bag-1',
    brandId: 'guess',
    brandName: 'Guess',
    brand: 'Guess',
    name: 'Mala Handbag Logo Print Guess',
    tier: 'mid',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=700&q=80',
    price: 160,
    fullPurchasePrice: 160,
    gender: 'feminino',
    occasion: 'cidade',
    sizes: ['Média'],
    colors: ['Castanho Logo', 'Preto'],
    description: 'Mala estruturada com estampado 4G monograma da Guess.'
  },
  {
    id: 'prod-mk-bag-1',
    brandId: 'michael-kors',
    brandName: 'Michael Kors',
    brand: 'Michael Kors',
    name: 'Mala de Ombro Jet Set Leather Michael Kors',
    tier: 'mid',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=700&q=80',
    price: 275,
    fullPurchasePrice: 275,
    gender: 'feminino',
    occasion: 'cidade',
    sizes: ['Média'],
    colors: ['Preto', 'Bege'],
    description: 'Mala de ombro em pele Saffiano resistente ideal para viagens.'
  },

  // LUXURY
  {
    id: 'prod-jacquemus-hat-1',
    brandId: 'jacquemus',
    brandName: 'Jacquemus',
    brand: 'Jacquemus',
    name: 'Chapéu Le Bob Artichaut Bucket Jacquemus',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    image: 'https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=700&q=80',
    price: 150,
    fullPurchasePrice: 150,
    gender: 'unissex',
    occasion: 'praia',
    sizes: ['Único'],
    colors: ['Bege', 'Preto'],
    description: 'O famoso chapéu bucket de abas desfiadas com cordão ajustável.'
  },
  {
    id: 'prod-acne-scarf-1',
    brandId: 'acne-studios',
    brandName: 'Acne Studios',
    brand: 'Acne Studios',
    name: 'Cachecol de Lã Alpaca Face Patch Acne Studios',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=700&q=80',
    price: 240,
    fullPurchasePrice: 240,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Rosa-Pálido', 'Cinzento'],
    description: 'Cachecol em mistura de lã alpaca ultra-macia com o patch emoji Face.'
  },
  {
    id: 'prod-loewe-wallet-1',
    brandId: 'loewe',
    brandName: 'LOEWE',
    brand: 'LOEWE',
    name: 'Carteira Puzzle Leather Cardholder LOEWE',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'wallet',
    image: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?auto=format&fit=crop&w=700&q=80',
    price: 320,
    fullPurchasePrice: 320,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Tan/Castanho', 'Preto'],
    description: 'Porta-cartões em pele de bezerro com o mítico corte geométrico Puzzle.'
  },
  {
    id: 'prod-lv-wallet-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Carteira Pocket Organizer Monogram Louis Vuitton',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'wallet',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=700&q=80',
    price: 380,
    fullPurchasePrice: 380,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Monogram Canvas'],
    description: 'Carteira compacta lendária em lona Monogram com acabamento em pele.'
  },
  {
    id: 'prod-saint-laurent-sunglasses-1',
    brandId: 'saint-laurent',
    brandName: 'Saint Laurent',
    brand: 'Saint Laurent',
    name: 'Óculos de Sol Acetato Black YSL Saint Laurent',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'sunglasses',
    image: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=700&q=80',
    price: 390,
    fullPurchasePrice: 390,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Preto'],
    description: 'Óculos de sol pretos com armação em acetato e assinatura YSL gravada.'
  },
  {
    id: 'prod-hermes-scarf-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Lenço de Seda Twilly Printed Hermès',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=700&q=80',
    price: 420,
    fullPurchasePrice: 420,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['Único'],
    colors: ['Laranja Hermès'],
    description: 'Fita/lenço em seda pura impressa à mão pelos artesãos de Lyon.'
  },
  {
    id: 'prod-gucci-belt-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Cinto GG Marmont Leather Belt Gucci',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'belt',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80',
    price: 450,
    fullPurchasePrice: 450,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['85cm', '90cm', '95cm'],
    colors: ['Preto com Fivela Dourada'],
    description: 'Cinto em pele lisa com a fivela com o duplo G icónico em latão.'
  },
  {
    id: 'prod-rolex-pouch-1',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Bolsa de Viagem em Pele para Relógio Rolex',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80',
    price: 450,
    fullPurchasePrice: 450,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['Único'],
    colors: ['Verde Rolex'],
    description: 'Estojo individual de viagem em pele verde oficial com forro em camurça.'
  },
  {
    id: 'prod-chanel-sunglasses-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Óculos de Sol Acetato Cat-Eye Chanel',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'sunglasses',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=700&q=80',
    price: 480,
    fullPurchasePrice: 480,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['Único'],
    colors: ['Preto com CC Dourado'],
    description: 'Óculos de sol em acetato preto com detalhes duplos C nas hastes.'
  },
  {
    id: 'prod-burberry-scarf-1',
    brandId: 'burberry',
    brandName: 'Burberry',
    brand: 'Burberry',
    name: 'Cachecol em Caxemira Vintage Check Burberry',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=700&q=80',
    price: 520,
    fullPurchasePrice: 520,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Único'],
    colors: ['Bege Camel Check'],
    description: 'Cachecol tecido numa fábrica tradicional escocesa com 100% caxemira pura.'
  },
  {
    id: 'prod-lv-belt-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Cinto Initiales 40mm Reversível Louis Vuitton',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'belt',
    image: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=700&q=80',
    price: 520,
    fullPurchasePrice: 520,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['90cm', '95cm', '100cm'],
    colors: ['Monogram / Preto'],
    description: 'Cinto reversível com fivela com iniciais LV em metal prateado.'
  },
  {
    id: 'prod-prada-hat-1',
    brandId: 'prada',
    brandName: 'Prada',
    brand: 'Prada',
    name: 'Chapéu Bucket Re-Nylon Black Prada',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'hat',
    image: 'https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=700&q=80',
    price: 550,
    fullPurchasePrice: 550,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['M', 'L'],
    colors: ['Preto'],
    description: 'O famoso chapéu bucket em Re-Nylon sustentável com o triângulo esmaltado.'
  },
  {
    id: 'prod-jacquemus-bag-1',
    brandId: 'jacquemus',
    brandName: 'Jacquemus',
    brand: 'Jacquemus',
    name: 'Carteira Le Chiquito Leather Jacquemus',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=80',
    price: 590,
    fullPurchasePrice: 590,
    gender: 'feminino',
    occasion: 'cidade',
    sizes: ['Mini'],
    colors: ['Bege', 'Preto'],
    description: 'A micro-mala em pele estruturada de asa rígida mais desejada.'
  },
  {
    id: 'prod-loewe-bag-1',
    brandId: 'loewe',
    brandName: 'LOEWE',
    brand: 'LOEWE',
    name: 'Mala Ráfia Anagram Basket Tote LOEWE',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=700&q=80',
    price: 690,
    fullPurchasePrice: 690,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['Média'],
    colors: ['Natural Palm / Tan Leather'],
    description: 'Cesto de praia tecido à mão em folhas de palmeira com asas em pele.'
  },
  {
    id: 'prod-hermes-belt-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Cinto em Pele de Bezerro H Buckle Hermès',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'belt',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80',
    price: 780,
    fullPurchasePrice: 780,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['85cm', '90cm', '95cm'],
    colors: ['Laranja Hermès / Preto'],
    description: 'Cinto reversível em pele Togo de grão refinado com a mítica fivela em H.'
  },
  {
    id: 'prod-rolex-cufflinks-1',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Botões de Punho Ouro 18k Crown Rolex',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'wallet',
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=700&q=80',
    price: 1800,
    fullPurchasePrice: 1800,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['Único'],
    colors: ['Ouro Amarelo 18k'],
    description: 'Botões de punho oficiais em ouro amarelo maciço de 18 quilates com a coroa Rolex.'
  },
  {
    id: 'prod-prada-bag-1',
    brandId: 'prada',
    brandName: 'Prada',
    brand: 'Prada',
    name: 'Mochila Re-Nylon & Leather Prada',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=700&q=80',
    price: 1850,
    fullPurchasePrice: 1850,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Média'],
    colors: ['Preto'],
    description: 'Mochila utilitária em Re-Nylon com acabamentos em pele Saffiano.'
  },
  {
    id: 'prod-gucci-bag-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Mala de Viagem GG Supreme Duffle Gucci',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80',
    price: 2200,
    fullPurchasePrice: 2200,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['Grande'],
    colors: ['GG Supreme Ébano'],
    description: 'Mala de viagem fim-de-semana clássica em lona GG Supreme.'
  },
  {
    id: 'prod-lv-bag-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Mala Keepall Bandoulière 50 Monogram Louis Vuitton',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=700&q=80',
    price: 2450,
    fullPurchasePrice: 2450,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['50cm'],
    colors: ['Monogram Canvas'],
    description: 'A mala de viagem dobrável em lona Monogram ícone da arte de viajar.'
  },
  {
    id: 'prod-chanel-bag-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Mala Clássica Flap Bag Lambskin Chanel',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=700&q=80',
    price: 8900,
    fullPurchasePrice: 8900,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['Média'],
    colors: ['Preto com CC Dourado'],
    description: 'A mala acolchoada icónica em pele de cordeiro com fecho giratório CC.'
  },
  {
    id: 'prod-hermes-bag-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Mala Birkin 30 Togo Leather Hermès',
    tier: 'luxury',
    category: 'acessorios',
    subCategory: 'bag',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=700&q=80',
    price: 12500,
    fullPurchasePrice: 12500,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['30cm'],
    colors: ['Gold / Laranja Hermès'],
    description: 'A mala de mão em pele Togo mais cobiçada e prestigiada da história.'
  },

  // ==========================================
  // 2. CALÇADO (calcado)
  // Tiers: Económico (eco), Médio (mid), Luxo (luxury)
  // ==========================================
  // ECO
  {
    id: 'prod-primark-sneakers-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Sapatilhas Canvas Low Top Primark',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',
    price: 16,
    fullPurchasePrice: 16,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['37', '38', '39', '40', '41', '42'],
    colors: ['Branco', 'Preto'],
    description: 'Sapatilhas de lona leve para passeios casuais na cidade.'
  },
  {
    id: 'prod-mango-sandals-1',
    brandId: 'mango',
    brandName: 'Mango',
    brand: 'Mango',
    name: 'Sandálias em Pele Leather Mango',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sandals',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=700&q=80',
    price: 49,
    fullPurchasePrice: 49,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['36', '37', '38', '39', '40'],
    colors: ['Tan', 'Preto'],
    description: 'Sandálias rasas em pele bovina com tiras cruzadas.'
  },
  {
    id: 'prod-vans-sneakers-1',
    brandId: 'vans',
    brandName: 'Vans',
    brand: 'Vans',
    name: 'Sapatilhas Old Skool Canvas Vans',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=700&q=80',
    price: 75,
    fullPurchasePrice: 75,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['37', '38', '39', '40', '41', '42'],
    colors: ['Preto/Branco', 'Azul'],
    description: 'Sapatilhas skate de cano baixo com a lendária risca Sidestripe.'
  },
  {
    id: 'prod-converse-sneakers-1',
    brandId: 'converse',
    brandName: 'Converse',
    brand: 'Converse',
    name: 'Sapatilhas Chuck Taylor All Star High Converse',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=700&q=80',
    price: 75,
    fullPurchasePrice: 75,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['37', '38', '39', '40', '41', '42'],
    colors: ['Preto', 'Branco'],
    description: 'As sapatilhas de lona de cano alto mais famosas da história.'
  },
  {
    id: 'prod-puma-sneakers-1',
    brandId: 'puma',
    brandName: 'Puma',
    brand: 'Puma',
    name: 'Sapatilhas Suede Classic Puma',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=700&q=80',
    price: 79,
    fullPurchasePrice: 79,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['38', '39', '40', '41', '42'],
    colors: ['Preto/Branco'],
    description: 'Sapatilhas clássicas em camurça macia com a risca Formstrip.'
  },
  {
    id: 'prod-adidas-sneakers-1',
    brandId: 'adidas',
    brandName: 'Adidas',
    brand: 'Adidas',
    name: 'Sapatilhas Stan Smith Leather Adidas',
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',
    price: 95,
    fullPurchasePrice: 95,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Branco/Verde'],
    description: 'Sapatilhas intemporais em pele branca com pormenor verde no calcanhar.'
  },
  {
    id: 'prod-nike-sneakers-1',
    brandId: 'nike',
    brandName: 'Nike',
    brand: 'Nike',
    name: "Sapatilhas Air Force 1 '07 Nike",
    tier: 'eco',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=700&q=80',
    price: 119,
    fullPurchasePrice: 119,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['38', '39', '40', '41', '42', '43'],
    colors: ['Branco Triplo'],
    description: 'As lendárias sapatilhas de basquetebol em pele branca impecável.'
  },

  // MID
  {
    id: 'prod-tommy-sneakers-1',
    brandId: 'tommy-hilfiger',
    brandName: 'Tommy Hilfiger',
    brand: 'Tommy Hilfiger',
    name: 'Sapatilhas Leather Court Sneakers Tommy Hilfiger',
    tier: 'mid',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=700&q=80',
    price: 120,
    fullPurchasePrice: 120,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39', '40', '41', '42', '43'],
    colors: ['Branco / Flag Tommy'],
    description: 'Sapatilhas em pele genuína com detalhes em risca Tommy.'
  },
  {
    id: 'prod-lacoste-sneakers-1',
    brandId: 'lacoste',
    brandName: 'Lacoste',
    brand: 'Lacoste',
    name: 'Sapatilhas Carnaby Leather Sneakers Lacoste',
    tier: 'mid',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=700&q=80',
    price: 130,
    fullPurchasePrice: 130,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['40', '41', '42', '43'],
    colors: ['Branco / Crocodilo Verde'],
    description: 'Sapatilhas de ténis em pele macia com crocodilo bordado.'
  },
  {
    id: 'prod-ax-sneakers-1',
    brandId: 'armani-exchange',
    brandName: 'Armani Exchange',
    brand: 'Armani Exchange',
    name: 'Sapatilhas Urban Runner Armani Exchange',
    tier: 'mid',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',
    price: 140,
    fullPurchasePrice: 140,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['40', '41', '42', '43'],
    colors: ['Preto/Branco'],
    description: 'Sapatilhas urbanas confortáveis com o logótipo A|X sobrensaído.'
  },
  {
    id: 'prod-boss-loafers-1',
    brandId: 'hugo-boss',
    brandName: 'Hugo Boss',
    brand: 'Hugo Boss',
    name: 'Mocassins Leather Loafers Hugo Boss',
    tier: 'mid',
    category: 'calcado',
    subCategory: 'loafers',
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=700&q=80',
    price: 220,
    fullPurchasePrice: 220,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['Preto', 'Castanho-Escuro'],
    description: 'Mocassins de alfaiataria em pele de bezerro de textura suave.'
  },

  // LUXURY
  {
    id: 'prod-common-sneakers-1',
    brandId: 'common-projects',
    brandName: 'Common Projects',
    brand: 'Common Projects',
    name: 'Sapatilhas Original Achilles Low White Common Projects',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=700&q=80',
    price: 420,
    fullPurchasePrice: 420,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Branco com Números Dourados'],
    description: 'A referência máxima de sapatilhas de luxo minimalistas feitas à mão em Itália.'
  },
  {
    id: 'prod-gucci-loafers-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Mocassins Horsebit Leather Loafers Gucci',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'loafers',
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=700&q=80',
    price: 850,
    fullPurchasePrice: 850,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['Preto', 'Castanho-Escuro'],
    description: 'Os lendários mocassins italianos criados em 1953 com travessão em latão.'
  },
  {
    id: 'prod-versace-sneakers-1',
    brandId: 'versace',
    brandName: 'Versace',
    brand: 'Versace',
    name: 'Sapatilhas Trigreca Sneakers Versace',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=700&q=80',
    price: 890,
    fullPurchasePrice: 890,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['40', '41', '42', '43'],
    colors: ['Branco/Dourado Barocco'],
    description: 'Sapatilhas esculturais com relevos no solado em padrão Greca.'
  },
  {
    id: 'prod-balenciaga-sneakers-1',
    brandId: 'balenciaga',
    brandName: 'Balenciaga',
    brand: 'Balenciaga',
    name: 'Sapatilhas Triple S Chunky Sneakers Balenciaga',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=700&q=80',
    price: 950,
    fullPurchasePrice: 950,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Branco/Cinzento/Preto'],
    description: 'As sapatilhas sobredimensionadas com sola tripla moldada de culto.'
  },
  {
    id: 'prod-lv-sneakers-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Sapatilhas LV Trainer Leather Louis Vuitton',
    tier: 'luxury',
    category: 'calcado',
    subCategory: 'sneakers',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',
    price: 1150,
    fullPurchasePrice: 1150,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['40', '41', '42', '43', '44'],
    colors: ['Branco/Azul LV'],
    description: 'Sapatilhas desenhadas por Virgil Abloh em pele de bezerro com detalhes Monogram.'
  },

  // ==========================================
  // 3. PERFUMES (perfumes)
  // Tiers: Económico (eco), Médio (mid), Luxo (luxury)
  // ==========================================
  // ECO
  {
    id: 'prod-hm-perfume-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Eau de Toilette Sunlit Palms H&M 75ml',
    tier: 'eco',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=700&q=80',
    price: 15,
    fullPurchasePrice: 15,
    gender: 'unissex',
    occasion: 'praia',
    sizes: ['75ml'],
    colors: ['Cristal'],
    description: 'Fragrância leve de praia com notas de água de coco e flor de laranjeira.'
  },
  {
    id: 'prod-zara-perfume-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Eau de Parfum Vibrant Leather Zara 100ml',
    tier: 'eco',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=700&q=80',
    price: 22,
    fullPurchasePrice: 22,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['100ml'],
    colors: ['Âmbar'],
    description: 'Fragrância lenhosa e fresca com notas de bergamota, couro e bambu.'
  },
  {
    id: 'prod-mango-perfume-1',
    brandId: 'mango',
    brandName: 'Mango',
    brand: 'Mango',
    name: 'Eau de Parfum Mediterranean Sun Mango 100ml',
    tier: 'eco',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=700&q=80',
    price: 25,
    fullPurchasePrice: 25,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['100ml'],
    colors: ['Âmbar'],
    description: 'Perfume solar com essência de figo mediterrânico e flor de sal.'
  },

  // MID
  {
    id: 'prod-ck-perfume-1',
    brandId: 'calvin-klein',
    brandName: 'Calvin Klein',
    brand: 'Calvin Klein',
    name: 'Eau de Toilette CK One Unisex Calvin Klein 100ml',
    tier: 'mid',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=700&q=80',
    price: 65,
    fullPurchasePrice: 65,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['100ml'],
    colors: ['Fosco'],
    description: 'A fragrância unissexo icónica de chá verde, papaia e bergamota.'
  },
  {
    id: 'prod-lacoste-perfume-1',
    brandId: 'lacoste',
    brandName: 'Lacoste',
    brand: 'Lacoste',
    name: 'Eau de Toilette L.12.12 Blanc Lacoste 100ml',
    tier: 'mid',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=700&q=80',
    price: 75,
    fullPurchasePrice: 75,
    gender: 'masculino',
    occasion: 'desporto',
    sizes: ['100ml'],
    colors: ['Branco'],
    description: 'Fragrância fresca desportiva com notas de toranja, alecrim e cedro.'
  },
  {
    id: 'prod-boss-perfume-1',
    brandId: 'hugo-boss',
    brandName: 'Hugo Boss',
    brand: 'Hugo Boss',
    name: 'Eau de Parfum Boss Bottled Hugo Boss 100ml',
    tier: 'mid',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=700&q=80',
    price: 95,
    fullPurchasePrice: 95,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['100ml'],
    colors: ['Âmbar'],
    description: 'Perfume elegante com notas de maçã, canela e madeiras nobres.'
  },

  // LUXURY
  {
    id: 'prod-chanel-perfume-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Perfume Chanel N°5 Eau de Parfum 100ml',
    tier: 'luxury',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=700&q=80',
    price: 165,
    fullPurchasePrice: 165,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['100ml'],
    colors: ['Âmbar'],
    description: 'O perfume mais mítico do mundo criado por Coco Chanel em 1921.'
  },
  {
    id: 'prod-hermes-perfume-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: "Perfume Terre d'Hermès Eau de Parfum 100ml",
    tier: 'luxury',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=700&q=80',
    price: 165,
    fullPurchasePrice: 165,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['100ml'],
    colors: ['Âmbar'],
    description: 'Uma fragrância mineral e amadeirada que liga o homem às suas origens.'
  },
  {
    id: 'prod-lv-perfume-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: "Perfume L'Immensité EDP 100ml Louis Vuitton",
    tier: 'luxury',
    category: 'perfumes',
    subCategory: 'perfume',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=700&q=80',
    price: 290,
    fullPurchasePrice: 290,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['100ml'],
    colors: ['Cristal'],
    description: 'Fragrância de viagem com notas de gengibre, toranja e âmbar amadeirado.'
  },

  // ==========================================
  // 4. RELÓGIOS (relogios)
  // Tiers: Económico (eco), Médio (mid), Luxo (luxury)
  // ==========================================
  // ECO
  {
    id: 'prod-hm-watch-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Relógio Analog Leather Strap H&M',
    tier: 'eco',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=700&q=80',
    price: 19,
    fullPurchasePrice: 19,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['38mm'],
    colors: ['Prata / Bracelete Castanha'],
    description: 'Relógio analógico de quartzo com caixa fina e bracelete sintética.'
  },
  {
    id: 'prod-zara-watch-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Relógio Digital Minimalist Steel Zara',
    tier: 'eco',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=700&q=80',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['40mm'],
    colors: ['Prata', 'Preto Matte'],
    description: 'Relógio digital de linhas minimalistas em aço inoxidável.'
  },

  // MID
  {
    id: 'prod-tommy-watch-1',
    brandId: 'tommy-hilfiger',
    brandName: 'Tommy Hilfiger',
    brand: 'Tommy Hilfiger',
    name: 'Relógio Multi-Dial Steel Tommy Hilfiger',
    tier: 'mid',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=700&q=80',
    price: 180,
    fullPurchasePrice: 180,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['44mm'],
    colors: ['Azul-Marinho / Prata'],
    description: 'Relógio multifunções em aço com mostrador azul e detalhes Tommy.'
  },
  {
    id: 'prod-boss-watch-1',
    brandId: 'hugo-boss',
    brandName: 'Hugo Boss',
    brand: 'Hugo Boss',
    name: 'Relógio Executive Leather Strap Hugo Boss',
    tier: 'mid',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80',
    price: 240,
    fullPurchasePrice: 240,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['42mm'],
    colors: ['Preto / Bracelete em Pele'],
    description: 'Relógio elegante de mostrador sunray e bracelete em pele croco.'
  },
  {
    id: 'prod-mk-watch-1',
    brandId: 'michael-kors',
    brandName: 'Michael Kors',
    brand: 'Michael Kors',
    name: 'Relógio Chronograph Rose Gold Michael Kors',
    tier: 'mid',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=700&q=80',
    price: 290,
    fullPurchasePrice: 290,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['42mm'],
    colors: ['Ouro Rosa'],
    description: 'Relógio cronógrafo marcante em aço com banho de ouro rosa.'
  },

  // LUXURY
  {
    id: 'prod-rolex-watch-1',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio Oyster Perpetual 36mm Steel Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=700&q=80',
    price: 6200,
    fullPurchasePrice: 6200,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['36mm'],
    colors: ['Oystersteel / Turquesa'],
    description: 'Relógio automático em aço Oystersteel com bracelete Oyster.'
  },
  {
    id: 'prod-rolex-watch-2',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio Datejust 41mm Fluted Bezel Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=700&q=80',
    price: 10500,
    fullPurchasePrice: 10500,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['41mm'],
    colors: ['Oystersteel & Ouro Branco'],
    description: 'Relógio de precisão com bisel canelado em ouro branco 18k.'
  },
  {
    id: 'prod-rolex-watch-3',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio Submariner Date 41mm Ceramic Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80',
    price: 14200,
    fullPurchasePrice: 14200,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['41mm'],
    colors: ['Oystersteel / Cerâmico Preto'],
    description: 'O relógio de mergulho mais famoso do mundo com bisel Cerachrom.'
  },
  {
    id: 'prod-rolex-watch-4',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio GMT-Master II "Pepsi" Steel Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=700&q=80',
    price: 16800,
    fullPurchasePrice: 16800,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['40mm'],
    colors: ['Oystersteel / Bisel Azul e Vermelho'],
    description: 'O relógio de aviação lendário de dois fusos horários.'
  },
  {
    id: 'prod-rolex-watch-5',
    brandId: 'rolex',
    brandName: 'Rolex',
    brand: 'Rolex',
    name: 'Relógio Daytona Cosmograph Gold 18k Rolex',
    tier: 'luxury',
    category: 'relogios',
    subCategory: 'watch',
    image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=700&q=80',
    price: 38000,
    fullPurchasePrice: 38000,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['40mm'],
    colors: ['Ouro Amarelo 18k'],
    description: 'O cronógrafo de corrida definitivo em ouro amarelo maciço 18k.'
  },

  // ==========================================
  // 5. ROUPA (roupa)
  // Tiers: Económico (eco), Médio (mid), Luxo (luxury)
  // ==========================================
  // ECO
  {
    id: 'prod-primark-tshirt-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'T-Shirt Básica Gola Redonda Primark',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=700&q=80',
    price: 7,
    fullPurchasePrice: 7,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto'],
    description: 'T-shirt básica leve em 100% algodão para uma viagem confortável.'
  },
  {
    id: 'prod-primark-swimwear-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Calção de Banho Quick-Dry Primark',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'swimwear',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=700&q=80',
    price: 12,
    fullPurchasePrice: 12,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L'],
    colors: ['Azul', 'Terracota'],
    description: 'Calções de banho leves com secagem rápida para dias de praia.'
  },
  {
    id: 'prod-bershka-tshirt-1',
    brandId: 'bershka',
    brandName: 'Bershka',
    brand: 'Bershka',
    name: 'T-Shirt Graphic Print Bershka',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=700&q=80',
    price: 15,
    fullPurchasePrice: 15,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Branco'],
    description: 'T-shirt com estampado gráfico urbano e corte moderno.'
  },
  {
    id: 'prod-hm-tshirt-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Pack 3 T-Shirts Regular Fit H&M',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=700&q=80',
    price: 18,
    fullPurchasePrice: 18,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto'],
    description: 'T-shirts básicas em algodão jersey macio de corte clássico.'
  },
  {
    id: 'prod-mango-tshirt-1',
    brandId: 'mango',
    brandName: 'Mango',
    brand: 'Mango',
    name: 'T-Shirt 100% Algodão Orgânico Mango',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=700&q=80',
    price: 18,
    fullPurchasePrice: 18,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege', 'Branco'],
    description: 'T-shirt de inspiração mediterrânica em algodão sustentável.'
  },
  {
    id: 'prod-primark-trousers-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Calça Chino Stretch Primark',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'trousers',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=700&q=80',
    price: 18,
    fullPurchasePrice: 18,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['38', '40', '42'],
    colors: ['Bege', 'Azul-Marinho'],
    description: 'Calça chino confortável com elastano para maior flexibilidade.'
  },
  {
    id: 'prod-pullbear-swimwear-1',
    brandId: 'pull-and-bear',
    brandName: 'Pull & Bear',
    brand: 'Pull & Bear',
    name: 'Calção de Banho Printed P&B',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'swimwear',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=700&q=80',
    price: 19,
    fullPurchasePrice: 19,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L'],
    colors: ['Estampado Palm'],
    description: 'Calção de banho leve com padrão tropical surfista.'
  },
  {
    id: 'prod-uniqlo-tshirt-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'T-Shirt AIRism Cotton Oversized Uniqlo',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=700&q=80',
    price: 19,
    fullPurchasePrice: 19,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto', 'Bege'],
    description: 'T-shirt de caimento oversized com exterior de algodão e interior fresco AIRism.'
  },
  {
    id: 'prod-zara-tshirt-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'T-Shirt Heavyweight Cotton Zara',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=700&q=80',
    price: 19,
    fullPurchasePrice: 19,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Terracota'],
    description: 'T-shirt em algodão denso de toque estruturado premium.'
  },
  {
    id: 'prod-hm-shirt-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Camisa Linen-Blend Resort H&M',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'shirt',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=700&q=80',
    price: 25,
    fullPurchasePrice: 25,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege', 'Branco'],
    description: 'Camisa fresca em mistura de linho e algodão com gola resort.'
  },
  {
    id: 'prod-bershka-trousers-1',
    brandId: 'bershka',
    brandName: 'Bershka',
    brand: 'Bershka',
    name: 'Calça Cargo Baggy Fit Bershka',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'trousers',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=700&q=80',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['36', '38', '40', '42'],
    colors: ['Caqui', 'Preto'],
    description: 'Calça cargo solta com bolsos laterais utilitários.'
  },
  {
    id: 'prod-hm-dress-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Vestido Slip Dress Floral H&M',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'dress',
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=700&q=80',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Estampado Floral'],
    description: 'Vestido fluido com alças finas reguláveis em tecido acetinado.'
  },
  {
    id: 'prod-pullbear-shirt-1',
    brandId: 'pull-and-bear',
    brandName: 'Pull & Bear',
    brand: 'Pull & Bear',
    name: 'Camisa Hawaiian Resort P&B',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'shirt',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=700&q=80',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Estampado Floral'],
    description: 'Camisa fresca de gola aberta com padrão de férias.'
  },
  {
    id: 'prod-gap-tshirt-1',
    brandId: 'gap',
    brandName: 'Gap',
    brand: 'Gap',
    name: 'Pack 3 T-Shirts Pocket Gap',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=700&q=80',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Cinzento'],
    description: 'T-shirts confortáveis com bolso no peito em 100% algodão.'
  },
  {
    id: 'prod-levis-tshirt-1',
    brandId: 'levis',
    brandName: "Levi's",
    brand: "Levi's",
    name: "T-Shirt Batwing Logo Levi's",
    tier: 'eco',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=700&q=80',
    price: 29,
    fullPurchasePrice: 29,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto'],
    description: "T-shirt icónica com estampado do logótipo asa de morcego Levi's."
  },
  {
    id: 'prod-uniqlo-shirt-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Camisa 100% Linho Premium Uniqlo',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'shirt',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=700&q=80',
    price: 39,
    fullPurchasePrice: 39,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Azul-Bebe'],
    description: 'Camisa confeccionada em 100% linho europeu de fibras longas.'
  },
  {
    id: 'prod-zara-shirt-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Camisa 100% Linho Riviera Zara',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'shirt',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=700&q=80',
    price: 39,
    fullPurchasePrice: 39,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege Natural', 'Branco'],
    description: 'Camisa de linho lavado com caimento descontraído de verão.'
  },
  {
    id: 'prod-uniqlo-trousers-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Calça Smart Ankle Chino Uniqlo',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'trousers',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=700&q=80',
    price: 45,
    fullPurchasePrice: 45,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege', 'Preto'],
    description: 'Calça chino com elasticidade bi-direcional e altura pelo tornozelo.'
  },
  {
    id: 'prod-zara-dress-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Vestido Satin Midi Slip Zara',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'dress',
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=700&q=80',
    price: 45,
    fullPurchasePrice: 45,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Terracota', 'Preto'],
    description: 'Vestido midi em tecido de cetim fluido com escote em V.'
  },
  {
    id: 'prod-hm-jacket-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Casaco Puffer Lightweight H&M',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=700&q=80',
    price: 49,
    fullPurchasePrice: 49,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Bege'],
    description: 'Casaco acolchoado leve e repelente de água com bolsa de arrumação.'
  },
  {
    id: 'prod-gap-hoodie-1',
    brandId: 'gap',
    brandName: 'Gap',
    brand: 'Gap',
    name: 'Hoodie Arch Logo Fleece Gap',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=700&q=80',
    price: 59,
    fullPurchasePrice: 59,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cinzento-Mescla', 'Azul-Marinho'],
    description: 'O clássico casaco com capuz e logótipo Gap bordado.'
  },
  {
    id: 'prod-uniqlo-jacket-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Casaco Ultra Light Down Uniqlo',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=700&q=80',
    price: 69,
    fullPurchasePrice: 69,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Azul-Marinho'],
    description: 'O famoso casaco de penas ultra-leve e dobrável em bolsa compacta.'
  },
  {
    id: 'prod-zara-blazer-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Blazer Structured Linen Blend Zara',
    tier: 'eco',
    category: 'roupa',
    subCategory: 'blazer',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=700&q=80',
    price: 79,
    fullPurchasePrice: 79,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['38', '40', '42', '44'],
    colors: ['Bege', 'Preto'],
    description: 'Blazer estruturado em mistura de linho leve com lapela de entalhe.'
  },
  {
    id: 'prod-levis-jeans-1',
    brandId: 'levis',
    brandName: "Levi's",
    brand: "Levi's",
    name: "Jeans 501 Original Straight Fit Levi's",
    tier: 'eco',
    category: 'roupa',
    subCategory: 'trousers',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=700&q=80',
    price: 99,
    fullPurchasePrice: 99,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['30', '32', '34', '36'],
    colors: ['Azul Denim Clássico'],
    description: 'Os jeans retos lendários originais criados em 1873 com fecho de botões.'
  },

  // MID
  {
    id: 'prod-superdry-tshirt-1',
    brandId: 'superdry',
    brandName: 'Superdry',
    brand: 'Superdry',
    name: 'T-Shirt Vintage Logo Superdry',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=700&q=80',
    price: 35,
    fullPurchasePrice: 35,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Cinzento-Mescla', 'Azul'],
    description: 'T-shirt em algodão macio com o estampado vintage Superdry.'
  },
  {
    id: 'prod-ck-tshirt-1',
    brandId: 'calvin-klein',
    brandName: 'Calvin Klein',
    brand: 'Calvin Klein',
    name: 'T-Shirt Monogram Logo Calvin Klein',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=700&q=80',
    price: 49,
    fullPurchasePrice: 49,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Preto'],
    description: 'T-shirt em algodão orgânico com estampado frontal CK.'
  },
  {
    id: 'prod-tommy-tshirt-1',
    brandId: 'tommy-hilfiger',
    brandName: 'Tommy Hilfiger',
    brand: 'Tommy Hilfiger',
    name: 'Polo Icon Flex Cotton Tommy Hilfiger',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=700&q=80',
    price: 89,
    fullPurchasePrice: 89,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul-Marinho', 'Branco'],
    description: 'Polo em piqué de algodão com toque suave e bandeira no peito.'
  },
  {
    id: 'prod-ck-jeans-1',
    brandId: 'calvin-klein',
    brandName: 'Calvin Klein',
    brand: 'Calvin Klein',
    name: 'Jeans Straight Fit Denim Calvin Klein',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'trousers',
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=700&q=80',
    price: 110,
    fullPurchasePrice: 110,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['30', '32', '34'],
    colors: ['Azul Denim'],
    description: 'Jeans de corte reto em algodão com elastano de grande conforto.'
  },
  {
    id: 'prod-lacoste-polo-1',
    brandId: 'lacoste',
    brandName: 'Lacoste',
    brand: 'Lacoste',
    name: 'Polo L.12.12 Classic Fit Lacoste',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=700&q=80',
    price: 110,
    fullPurchasePrice: 110,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Verde-Crocodilo', 'Branco'],
    description: 'O polo de ténis original criado por René Lacoste em 1933.'
  },
  {
    id: 'prod-ralph-tshirt-1',
    brandId: 'ralph-lauren',
    brandName: 'Ralph Lauren',
    brand: 'Ralph Lauren',
    name: 'Polo Custom Slim Fit Polo Ralph Lauren',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=700&q=80',
    price: 130,
    fullPurchasePrice: 130,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul-Marinho', 'Branco'],
    description: 'O mítico polo de algodão piqué da Polo Ralph Lauren.'
  },
  {
    id: 'prod-diesel-jeans-1',
    brandId: 'diesel',
    brandName: 'Diesel',
    brand: 'Diesel',
    name: 'Jeans 1979 Sleenker Slim Denim Diesel',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'trousers',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=700&q=80',
    price: 190,
    fullPurchasePrice: 190,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['30', '32', '34'],
    colors: ['Azul Denim Escuro'],
    description: 'Jeans slim de confeção italiana com lavagem vintage premium.'
  },
  {
    id: 'prod-tommy-jacket-1',
    brandId: 'tommy-hilfiger',
    brandName: 'Tommy Hilfiger',
    brand: 'Tommy Hilfiger',
    name: 'Casaco Puffer Lightweight Tommy Hilfiger',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=700&q=80',
    price: 220,
    fullPurchasePrice: 220,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul-Marinho'],
    description: 'Casaco térmico leve com enchimento reciclável e bandeira Tommy.'
  },
  {
    id: 'prod-tnf-jacket-1',
    brandId: 'the-north-face',
    brandName: 'The North Face',
    brand: 'The North Face',
    name: 'Casaco Puffer Nuptse 1996 Down Jacket TNF',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=700&q=80',
    price: 340,
    fullPurchasePrice: 340,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Azul-Cobalto'],
    description: 'O lendário casaco de penas térmico com enchimento de penas 700 fill.'
  },
  {
    id: 'prod-boss-blazer-1',
    brandId: 'hugo-boss',
    brandName: 'Hugo Boss',
    brand: 'Hugo Boss',
    name: 'Fato Tailored Wool Blend Suit Hugo Boss',
    tier: 'mid',
    category: 'roupa',
    subCategory: 'blazer',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=700&q=80',
    price: 690,
    fullPurchasePrice: 690,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['48', '50', '52'],
    colors: ['Azul-Marinho'],
    description: 'Fato completo de corte impecável em lã virgem italiana.'
  },

  // LUXURY
  {
    id: 'prod-jacquemus-shirt-1',
    brandId: 'jacquemus',
    brandName: 'Jacquemus',
    brand: 'Jacquemus',
    name: 'Camisa de Linho La Chemise Jean Jacquemus',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'shirt',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=700&q=80',
    price: 320,
    fullPurchasePrice: 320,
    gender: 'masculino',
    occasion: 'praia',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege Natural'],
    description: 'Camisa de linho desconstruída com o logótipo Jacquemus bordado.'
  },
  {
    id: 'prod-acne-jeans-1',
    brandId: 'acne-studios',
    brandName: 'Acne Studios',
    brand: 'Acne Studios',
    name: 'Jeans Straight Fit Loose Denim Acne Studios',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'trousers',
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=700&q=80',
    price: 340,
    fullPurchasePrice: 340,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['30', '32', '34'],
    colors: ['Azul Vintage Wash'],
    description: 'Denim rígido de alta qualidade com corte direto descontraído.'
  },
  {
    id: 'prod-saint-laurent-tshirt-1',
    brandId: 'saint-laurent',
    brandName: 'Saint Laurent',
    brand: 'Saint Laurent',
    name: 'T-Shirt Cotton Logo Saint Laurent',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=700&q=80',
    price: 420,
    fullPurchasePrice: 420,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Branco'],
    description: 'T-shirt em jersey de algodão ultra-fino com corte rock parisiense.'
  },
  {
    id: 'prod-burberry-shirt-1',
    brandId: 'burberry',
    brandName: 'Burberry',
    brand: 'Burberry',
    name: 'Camisa Vintage Check Cotton Burberry',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'shirt',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=700&q=80',
    price: 480,
    fullPurchasePrice: 480,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Bege Vintage Check'],
    description: 'Camisa em sapatilha de algodão com o padrão de xadrez icónico.'
  },
  {
    id: 'prod-zimmermann-top-1',
    brandId: 'zimmermann',
    brandName: 'Zimmermann',
    brand: 'Zimmermann',
    name: 'Top de Seda Floral Matchmaker Zimmermann',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'tshirt',
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=700&q=80',
    price: 580,
    fullPurchasePrice: 580,
    gender: 'feminino',
    occasion: 'praia',
    sizes: ['0', '1', '2'],
    colors: ['Estampado Floral Resort'],
    description: 'Top leve em 100% seda organza com folhos finos delicados.'
  },
  {
    id: 'prod-zimmermann-dress-1',
    brandId: 'zimmermann',
    brandName: 'Zimmermann',
    brand: 'Zimmermann',
    name: 'Vestido Matchmaker Floral Silk Midi Zimmermann',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'dress',
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=700&q=80',
    price: 950,
    fullPurchasePrice: 950,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['0', '1', '2'],
    colors: ['Estampado Floral Victorian'],
    description: 'Vestido de alta-costura em seda pura com cinto e estampado floral.'
  },
  {
    id: 'prod-acne-coat-1',
    brandId: 'acne-studios',
    brandName: 'Acne Studios',
    brand: 'Acne Studios',
    name: 'Casaco Wool Blend Oversized Coat Acne Studios',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=700&q=80',
    price: 1100,
    fullPurchasePrice: 1100,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['46', '48', '50'],
    colors: ['Camel'],
    description: 'Sobretudo duplo em malha de lã estruturada de caimento arquitetónico.'
  },
  {
    id: 'prod-versace-shirt-1',
    brandId: 'versace',
    brandName: 'Versace',
    brand: 'Versace',
    name: 'Camisa em Seda Barocco Print Versace',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'shirt',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=700&q=80',
    price: 1150,
    fullPurchasePrice: 1150,
    gender: 'masculino',
    occasion: 'formal',
    sizes: ['48', '50', '52'],
    colors: ['Barocco Dourado/Preto'],
    description: 'Camisa de seda pura twill com a estampa opulenta barroca.'
  },
  {
    id: 'prod-loewe-dress-1',
    brandId: 'loewe',
    brandName: 'LOEWE',
    brand: 'LOEWE',
    name: 'Vestido Asymmetrical Linen LOEWE',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'dress',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=700&q=80',
    price: 1850,
    fullPurchasePrice: 1850,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['36', '38', '40'],
    colors: ['Branco Ecru'],
    description: 'Vestido de linho escultural com corte assimétrico vanguardista.'
  },
  {
    id: 'prod-gucci-jacket-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Casaco Jacquard GG Monogram Gucci',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=700&q=80',
    price: 1950,
    fullPurchasePrice: 1950,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['48', '50', '52'],
    colors: ['Castanho GG'],
    description: 'Casaco com fecho de correr em lona jacquard GG e riscas Web.'
  },
  {
    id: 'prod-balenciaga-jacket-1',
    brandId: 'balenciaga',
    brandName: 'Balenciaga',
    brand: 'Balenciaga',
    name: 'Casaco Puffer Oversized Balenciaga',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=700&q=80',
    price: 2100,
    fullPurchasePrice: 2100,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['46', '48', '50'],
    colors: ['Preto Matte'],
    description: 'Puffer volumoso em nylon técnico impermeável com gola alta.'
  },
  {
    id: 'prod-burberry-coat-1',
    brandId: 'burberry',
    brandName: 'Burberry',
    brand: 'Burberry',
    name: 'Trench Coat Kensington Heritage Burberry',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=700&q=80',
    price: 2250,
    fullPurchasePrice: 2250,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['48', '50', '52'],
    colors: ['Honey / Bege'],
    description: 'O lendário trench coat britânico duplo em gabardina de algodão.'
  },
  {
    id: 'prod-prada-blazer-1',
    brandId: 'prada',
    brandName: 'Prada',
    brand: 'Prada',
    name: 'Blazer Re-Nylon Tailored Prada',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'blazer',
    image: 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=700&q=80',
    price: 2400,
    fullPurchasePrice: 2400,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['48', '50', '52'],
    colors: ['Preto'],
    description: 'Blazer de alfaiataria em Re-Nylon com bolso de peito e emblema.'
  },
  {
    id: 'prod-chanel-cardigan-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Cardigan de Tweed Wool Blend Chanel',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=700&q=80',
    price: 2800,
    fullPurchasePrice: 2800,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['36', '38', '40'],
    colors: ['Preto/Branco Tweed'],
    description: 'Casaco de tweed parisiense com botões de joia gravados com o logo CC.'
  },
  {
    id: 'prod-hermes-coat-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Manteau em Lã e Caxemira Double-Face Hermès',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=700&q=80',
    price: 3400,
    fullPurchasePrice: 3400,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['48', '50'],
    colors: ['Camel'],
    description: 'Sobretudo longo em lã e caxemira cosido à mão pelos mestres artesãos.'
  },
  {
    id: 'prod-saint-laurent-jacket-1',
    brandId: 'saint-laurent',
    brandName: 'Saint Laurent',
    brand: 'Saint Laurent',
    name: 'Blusão de Pele Moto Leather Jacket Saint Laurent',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'jacket',
    image: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=700&q=80',
    price: 3900,
    fullPurchasePrice: 3900,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['48', '50', '52'],
    colors: ['Preto'],
    description: 'Blusão de pele de cordeiro macia com fivelas e fechos metálicos YSL.'
  },
  {
    id: 'prod-chanel-dress-1',
    brandId: 'chanel',
    brandName: 'Chanel',
    brand: 'Chanel',
    name: 'Vestido Midi Silk Jacquard Chanel',
    tier: 'luxury',
    category: 'roupa',
    subCategory: 'dress',
    image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=700&q=80',
    price: 4200,
    fullPurchasePrice: 4200,
    gender: 'feminino',
    occasion: 'formal',
    sizes: ['36', '38', '40'],
    colors: ['Preto'],
    description: 'Vestido midi em seda jacquard preta com caimento de alta-costura.'
  },

  // ==========================================
  // 6. ROUPA INTERIOR (roupainterior)
  // Tiers: Económico (eco), Médio (mid), Luxo (luxury)
  // ==========================================
  // ECO
  {
    id: 'prod-primark-socks-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Pack 5 Pares Meias Algodão Primark',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=700&q=80',
    price: 6,
    fullPurchasePrice: 6,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['35-38', '39-42', '43-46'],
    colors: ['Branco', 'Preto'],
    description: 'Pack de 5 pares de meias respiráveis em algodão macio para o dia a dia.'
  },
  {
    id: 'prod-primark-underwear-1',
    brandId: 'primark',
    brandName: 'Primark',
    brand: 'Primark',
    name: 'Pack 3 Boxer Shorts Algodão Primark',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'underwear',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=700&q=80',
    price: 8,
    fullPurchasePrice: 8,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Azul-Marinho'],
    description: 'Pack de 3 boxers em algodão com cintura elástica.'
  },
  {
    id: 'prod-hm-socks-1',
    brandId: 'h-and-m',
    brandName: 'H&M',
    brand: 'H&M',
    name: 'Pack 7 Pares Meias Invisíveis H&M',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=700&q=80',
    price: 10,
    fullPurchasePrice: 10,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['36-39', '40-43'],
    colors: ['Branco', 'Nude'],
    description: 'Meias curtas invisíveis com banda em silicone no calcanhar.'
  },
  {
    id: 'prod-uniqlo-socks-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Pack 3 Pares Meias AIRism Uniqlo',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=700&q=80',
    price: 12,
    fullPurchasePrice: 12,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Preto', 'Branco'],
    description: 'Meias com tecnologia AIRism de secagem ultra-rápida anti-odor.'
  },
  {
    id: 'prod-zara-socks-1',
    brandId: 'zara',
    brandName: 'Zara',
    brand: 'Zara',
    name: 'Pack 3 Pares Meias Ribbed Zara',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=700&q=80',
    price: 12,
    fullPurchasePrice: 12,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Ecru', 'Preto'],
    description: 'Meias de cano médio em malha canelada de algodão.'
  },
  {
    id: 'prod-levis-socks-1',
    brandId: 'levis',
    brandName: "Levi's",
    brand: "Levi's",
    name: "Pack 2 Pares Meias Tab Logo Levi's",
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=700&q=80',
    price: 14,
    fullPurchasePrice: 14,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Branco', 'Preto'],
    description: "Meias caneladas com a mítica etiqueta Red Tab da Levi's."
  },
  {
    id: 'prod-adidas-socks-1',
    brandId: 'adidas',
    brandName: 'Adidas',
    brand: 'Adidas',
    name: 'Pack 3 Pares Meias Cushioned Crew Adidas',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=700&q=80',
    price: 14,
    fullPurchasePrice: 14,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['39-42', '43-46'],
    colors: ['Branco', 'Preto'],
    description: 'Meias de cano alto com acolchoamento na planta do pé.'
  },
  {
    id: 'prod-uniqlo-underwear-1',
    brandId: 'uniqlo',
    brandName: 'Uniqlo',
    brand: 'Uniqlo',
    name: 'Pack 2 Cuecas Boxers AIRism Seamless Uniqlo',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'underwear',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=700&q=80',
    price: 15,
    fullPurchasePrice: 15,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Azul-Marinho'],
    description: 'Boxers sem costuras invisíveis sob a roupa para máximo conforto.'
  },
  {
    id: 'prod-nike-socks-1',
    brandId: 'nike',
    brandName: 'Nike',
    brand: 'Nike',
    name: 'Pack 3 Pares Meias Everyday Cushion Nike',
    tier: 'eco',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=700&q=80',
    price: 16,
    fullPurchasePrice: 16,
    gender: 'unissex',
    occasion: 'desporto',
    sizes: ['38-42', '42-46'],
    colors: ['Branco', 'Preto'],
    description: 'Meias desportivas com tecnologia Dri-FIT que absorve a transpiração.'
  },

  // MID
  {
    id: 'prod-tommy-socks-1',
    brandId: 'tommy-hilfiger',
    brandName: 'Tommy Hilfiger',
    brand: 'Tommy Hilfiger',
    name: 'Pack 2 Pares Meias Flag Tommy Hilfiger',
    tier: 'mid',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=700&q=80',
    price: 22,
    fullPurchasePrice: 22,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Azul-Marinho', 'Branco'],
    description: 'Meias finas em algodão com bordado da bandeira Tommy.'
  },
  {
    id: 'prod-ralph-socks-1',
    brandId: 'ralph-lauren',
    brandName: 'Ralph Lauren',
    brand: 'Ralph Lauren',
    name: 'Pack 3 Pares Meias Polo Player Ralph Lauren',
    tier: 'mid',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=700&q=80',
    price: 35,
    fullPurchasePrice: 35,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Azul-Marinho', 'Bege'],
    description: 'Meias elegantes com bordado do cavalo Polo em contraste.'
  },
  {
    id: 'prod-ck-underwear-1',
    brandId: 'calvin-klein',
    brandName: 'Calvin Klein',
    brand: 'Calvin Klein',
    name: 'Pack 3 Trunk Underwear Cotton Stretch CK',
    tier: 'mid',
    category: 'roupainterior',
    subCategory: 'underwear',
    image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=700&q=80',
    price: 45,
    fullPurchasePrice: 45,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Preto', 'Cinzento', 'Branco'],
    description: 'Boxers icónicos em algodão com a famosa faixa elástica Calvin Klein.'
  },

  // LUXURY
  {
    id: 'prod-versace-underwear-1',
    brandId: 'versace',
    brandName: 'Versace',
    brand: 'Versace',
    name: 'Boxer Brief Barocco Print Versace',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'underwear',
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=700&q=80',
    price: 95,
    fullPurchasePrice: 95,
    gender: 'masculino',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L'],
    colors: ['Preto/Dourado Barocco'],
    description: 'Boxers em algodão elástico com elástico na cintura em padrão Greca e Medusa.'
  },
  {
    id: 'prod-balenciaga-socks-1',
    brandId: 'balenciaga',
    brandName: 'Balenciaga',
    brand: 'Balenciaga',
    name: 'Meias Balenciaga Tennis Logo Socks',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=700&q=80',
    price: 110,
    fullPurchasePrice: 110,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['39-42', '43-46'],
    colors: ['Branco/Preto'],
    description: 'Meias de ténis em malha canelada com o logótipo Balenciaga tricotado.'
  },
  {
    id: 'prod-hermes-socks-1',
    brandId: 'hermes',
    brandName: 'Hermès',
    brand: 'Hermès',
    name: 'Meias em Algodão Mercerizado Hermès',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=700&q=80',
    price: 120,
    fullPurchasePrice: 120,
    gender: 'unissex',
    occasion: 'formal',
    sizes: ['39-42', '43-46'],
    colors: ['Azul-Marinho', 'Preto'],
    description: 'Meias ultra-refinadas em algodão egípcio mercerizado com detalhe H.'
  },
  {
    id: 'prod-gucci-socks-1',
    brandId: 'gucci',
    brandName: 'Gucci',
    brand: 'Gucci',
    name: 'Meias GG Monogram Cotton Blend Gucci',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=700&q=80',
    price: 130,
    fullPurchasePrice: 130,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['S', 'M', 'L'],
    colors: ['Bege/Castanho GG'],
    description: 'Meias de luxo com o lendário padrão monograma GG de Guccio Gucci.'
  },
  {
    id: 'prod-lv-socks-1',
    brandId: 'louis-vuitton',
    brandName: 'Louis Vuitton',
    brand: 'Louis Vuitton',
    name: 'Meias Monogram Jacquard Cotton Louis Vuitton',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=700&q=80',
    price: 140,
    fullPurchasePrice: 140,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['M', 'L'],
    colors: ['Preto', 'Castanho Monogram'],
    description: 'Meias em jacquard de algodão fino tecidas com o icónico padrão Monogram.'
  },
  {
    id: 'prod-prada-socks-1',
    brandId: 'prada',
    brandName: 'Prada',
    brand: 'Prada',
    name: 'Pack 3 Pares Meias Prada Triangle Logo',
    tier: 'luxury',
    category: 'roupainterior',
    subCategory: 'socks',
    image: 'https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=700&q=80',
    price: 150,
    fullPurchasePrice: 150,
    gender: 'unissex',
    occasion: 'cidade',
    sizes: ['M', 'L'],
    colors: ['Preto', 'Branco'],
    description: 'Meias de algodão de malha fina com o emblema em triângulo Prada.'
  }
];

// Map and calculate fields cleanly, ensuring exact sorting by category (A-Z) and then price (ascending)
export const PRODUCTS = RAW_PRODUCTS.map((item) => {
  const finalPrice = item.price || item.fullPurchasePrice || 50;
  const rentalPricePerDay = Math.max(3, Math.round(finalPrice / 25));
  const image = item.image || importProductImages(item.category, item.subCategory);

  return {
    ...item,
    brand: item.brand || item.brandName,
    brandName: item.brandName || item.brand,
    price: finalPrice,
    fullPurchasePrice: finalPrice,
    rentalPricePerDay,
    image,
    images: [image],
    inStock: true,
    discontinued: false,
    merchantAttribution: `${item.brandName} Partner Network`,
    affiliateUrl: `https://partner.bagless.app/redirect?brand=${item.brandId}&id=${item.id}`,
    weatherTag: item.occasion === 'praia' ? 'Clima Quente' : item.occasion === 'desporto' ? 'Desporto & Aventura' : 'Urbano & Elegante'
  };
}).sort((a, b) => {
  // Sort 1: Category alphabetically
  const categoryCompare = a.category.localeCompare(b.category);
  if (categoryCompare !== 0) return categoryCompare;

  // Sort 2: Price from cheapest to most expensive within category
  return a.price - b.price;
});

export const DYNAMIC_CATALOG = PRODUCTS;

/**
 * Periodically syncs products from partner feeds
 */
export const syncLiveProductFeeds = async () => {
  console.log(`[Bagless Feed Sync] Catálogo com ${PRODUCTS.length} produtos balanceados nos 3 tiers.`);
  return PRODUCTS;
};

export { importProductImages, FALLBACK_IMAGE };
